// This file is auto-generated by @hey-api/openapi-ts

export const AdditionalRemarkCreateSchema = {
    properties: {
        registration_date: {
            type: 'string',
            format: 'date',
            title: 'Registration Date'
        },
        content: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Content'
        },
        display_order: {
            type: 'integer',
            title: 'Display Order',
            default: 0
        },
        resume_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Resume Id'
        }
    },
    type: 'object',
    required: ['registration_date'],
    title: 'AdditionalRemarkCreate'
} as const;

export const AdditionalRemarkReadSchema = {
    properties: {
        registration_date: {
            type: 'string',
            format: 'date',
            title: 'Registration Date'
        },
        content: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Content'
        },
        display_order: {
            type: 'integer',
            title: 'Display Order',
            default: 0
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        resume_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Resume Id'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['registration_date', 'id', 'created_at'],
    title: 'AdditionalRemarkRead'
} as const;

export const AuthStatusSchema = {
    properties: {
        healthy: {
            type: 'boolean',
            title: 'Healthy'
        }
    },
    type: 'object',
    required: ['healthy'],
    title: 'AuthStatus'
} as const;

export const AwardCreateSchema = {
    properties: {
        award_date: {
            type: 'string',
            format: 'date',
            title: 'Award Date'
        },
        category: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Category'
        },
        details: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Details'
        },
        awarding_institution: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Awarding Institution'
        },
        display_order: {
            type: 'integer',
            title: 'Display Order',
            default: 0
        },
        resume_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Resume Id'
        }
    },
    type: 'object',
    required: ['award_date'],
    title: 'AwardCreate'
} as const;

export const AwardReadSchema = {
    properties: {
        award_date: {
            type: 'string',
            format: 'date',
            title: 'Award Date'
        },
        category: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Category'
        },
        details: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Details'
        },
        awarding_institution: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Awarding Institution'
        },
        display_order: {
            type: 'integer',
            title: 'Display Order',
            default: 0
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        resume_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Resume Id'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['award_date', 'id', 'created_at'],
    title: 'AwardRead'
} as const;

export const CertificationCreateSchema = {
    properties: {
        acquisition_date: {
            type: 'string',
            format: 'date',
            title: 'Acquisition Date'
        },
        certification_name: {
            type: 'string',
            title: 'Certification Name'
        },
        remarks: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Remarks'
        },
        display_order: {
            type: 'integer',
            title: 'Display Order',
            default: 0
        },
        resume_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Resume Id'
        }
    },
    type: 'object',
    required: ['acquisition_date', 'certification_name'],
    title: 'CertificationCreate'
} as const;

export const CertificationReadSchema = {
    properties: {
        acquisition_date: {
            type: 'string',
            format: 'date',
            title: 'Acquisition Date'
        },
        certification_name: {
            type: 'string',
            title: 'Certification Name'
        },
        remarks: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Remarks'
        },
        display_order: {
            type: 'integer',
            title: 'Display Order',
            default: 0
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        resume_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Resume Id'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['acquisition_date', 'certification_name', 'id', 'created_at'],
    title: 'CertificationRead'
} as const;

export const DisciplineRecordCreateSchema = {
    properties: {
        record_date: {
            type: 'string',
            format: 'date',
            title: 'Record Date'
        },
        type: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Type'
        },
        reason: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Reason'
        },
        display_order: {
            type: 'integer',
            title: 'Display Order',
            default: 0
        },
        resume_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Resume Id'
        }
    },
    type: 'object',
    required: ['record_date'],
    title: 'DisciplineRecordCreate'
} as const;

export const DisciplineRecordReadSchema = {
    properties: {
        record_date: {
            type: 'string',
            format: 'date',
            title: 'Record Date'
        },
        type: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Type'
        },
        reason: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Reason'
        },
        display_order: {
            type: 'integer',
            title: 'Display Order',
            default: 0
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        resume_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Resume Id'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['record_date', 'id', 'created_at'],
    title: 'DisciplineRecordRead'
} as const;

export const EducationHistoryCreateSchema = {
    properties: {
        start_date: {
            type: 'string',
            format: 'date',
            title: 'Start Date'
        },
        end_date: {
            type: 'string',
            format: 'date',
            title: 'End Date'
        },
        institution: {
            type: 'string',
            title: 'Institution'
        },
        major: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Major'
        },
        graduation_type: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Graduation Type'
        },
        degree: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Degree'
        },
        display_order: {
            type: 'integer',
            title: 'Display Order',
            default: 0
        },
        resume_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Resume Id'
        }
    },
    type: 'object',
    required: ['start_date', 'end_date', 'institution'],
    title: 'EducationHistoryCreate'
} as const;

export const EducationHistoryReadSchema = {
    properties: {
        start_date: {
            type: 'string',
            format: 'date',
            title: 'Start Date'
        },
        end_date: {
            type: 'string',
            format: 'date',
            title: 'End Date'
        },
        institution: {
            type: 'string',
            title: 'Institution'
        },
        major: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Major'
        },
        graduation_type: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Graduation Type'
        },
        degree: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Degree'
        },
        display_order: {
            type: 'integer',
            title: 'Display Order',
            default: 0
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        resume_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Resume Id'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['start_date', 'end_date', 'institution', 'id', 'created_at'],
    title: 'EducationHistoryRead'
} as const;

export const EmailVerificationTokenReadSchema = {
    properties: {
        token: {
            type: 'string',
            title: 'Token'
        },
        expires_at: {
            type: 'string',
            format: 'date-time',
            title: 'Expires At'
        },
        used_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Used At'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        user_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'User Id'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['token', 'expires_at', 'id', 'created_at'],
    title: 'EmailVerificationTokenRead'
} as const;

export const FamilyMemberCreateSchema = {
    properties: {
        relationship: {
            type: 'string',
            title: 'Relationship'
        },
        name: {
            type: 'string',
            title: 'Name'
        },
        birth_date: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Birth Date'
        },
        blessed: {
            type: 'boolean',
            title: 'Blessed',
            default: false
        },
        remarks: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Remarks'
        },
        display_order: {
            type: 'integer',
            title: 'Display Order',
            default: 0
        },
        resume_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Resume Id'
        }
    },
    type: 'object',
    required: ['relationship', 'name'],
    title: 'FamilyMemberCreate'
} as const;

export const FamilyMemberReadSchema = {
    properties: {
        relationship: {
            type: 'string',
            title: 'Relationship'
        },
        name: {
            type: 'string',
            title: 'Name'
        },
        birth_date: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Birth Date'
        },
        blessed: {
            type: 'boolean',
            title: 'Blessed',
            default: false
        },
        remarks: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Remarks'
        },
        display_order: {
            type: 'integer',
            title: 'Display Order',
            default: 0
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        resume_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Resume Id'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['relationship', 'name', 'id', 'created_at'],
    title: 'FamilyMemberRead'
} as const;

export const GoogleAuthActivateSchema = {
    properties: {
        google_id: {
            type: 'string',
            maxLength: 255,
            minLength: 5,
            title: 'Google Id'
        },
        google_refresh_token: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Google Refresh Token'
        },
        google_access_token: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Google Access Token'
        }
    },
    type: 'object',
    required: ['google_id'],
    title: 'GoogleAuthActivate'
} as const;

export const GoogleTokenUpdateSchema = {
    properties: {
        google_refresh_token: {
            type: 'string',
            minLength: 10,
            title: 'Google Refresh Token'
        },
        google_access_token: {
            type: 'string',
            minLength: 10,
            title: 'Google Access Token'
        }
    },
    type: 'object',
    required: ['google_refresh_token', 'google_access_token'],
    title: 'GoogleTokenUpdate'
} as const;

export const HTTPValidationErrorSchema = {
    properties: {
        detail: {
            items: {
                '$ref': '#/components/schemas/ValidationError'
            },
            type: 'array',
            title: 'Detail'
        }
    },
    type: 'object',
    title: 'HTTPValidationError'
} as const;

export const LoginRequestSchema = {
    properties: {
        identifier: {
            type: 'string',
            minLength: 1,
            title: 'Identifier'
        },
        password: {
            type: 'string',
            minLength: 8,
            title: 'Password'
        }
    },
    type: 'object',
    required: ['identifier', 'password'],
    title: 'LoginRequest'
} as const;

export const LoginResponseSchema = {
    properties: {
        access_token: {
            type: 'string',
            title: 'Access Token'
        },
        token_type: {
            type: 'string',
            const: 'bearer',
            title: 'Token Type',
            default: 'bearer'
        },
        expires_in: {
            type: 'integer',
            minimum: 0,
            title: 'Expires In'
        },
        user: {
            '$ref': '#/components/schemas/UserRead'
        }
    },
    type: 'object',
    required: ['access_token', 'expires_in', 'user'],
    title: 'LoginResponse'
} as const;

export const OrganizationalActivityCreateSchema = {
    properties: {
        start_date: {
            type: 'string',
            format: 'date',
            title: 'Start Date'
        },
        end_date: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date'
                },
                {
                    type: 'null'
                }
            ],
            title: 'End Date'
        },
        organization_name: {
            type: 'string',
            title: 'Organization Name'
        },
        position: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Position'
        },
        main_role: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Main Role'
        },
        display_order: {
            type: 'integer',
            title: 'Display Order',
            default: 0
        },
        resume_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Resume Id'
        }
    },
    type: 'object',
    required: ['start_date', 'organization_name'],
    title: 'OrganizationalActivityCreate'
} as const;

export const OrganizationalActivityReadSchema = {
    properties: {
        start_date: {
            type: 'string',
            format: 'date',
            title: 'Start Date'
        },
        end_date: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date'
                },
                {
                    type: 'null'
                }
            ],
            title: 'End Date'
        },
        organization_name: {
            type: 'string',
            title: 'Organization Name'
        },
        position: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Position'
        },
        main_role: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Main Role'
        },
        display_order: {
            type: 'integer',
            title: 'Display Order',
            default: 0
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        resume_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Resume Id'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['start_date', 'organization_name', 'id', 'created_at'],
    title: 'OrganizationalActivityRead'
} as const;

export const PasswordResetConfirmSchema = {
    properties: {
        token: {
            type: 'string',
            title: 'Token'
        },
        new_password: {
            type: 'string',
            minLength: 8,
            title: 'New Password'
        }
    },
    type: 'object',
    required: ['token', 'new_password'],
    title: 'PasswordResetConfirm'
} as const;

export const PasswordResetRequestSchema = {
    properties: {
        identifier: {
            type: 'string',
            minLength: 1,
            title: 'Identifier',
            description: 'Username, email, or user ID for the account.'
        }
    },
    type: 'object',
    required: ['identifier'],
    title: 'PasswordResetRequest'
} as const;

export const PasswordResetTokenSchema = {
    properties: {
        token: {
            type: 'string',
            title: 'Token'
        }
    },
    type: 'object',
    required: ['token'],
    title: 'PasswordResetToken'
} as const;

export const PersonalProfileCreateSchema = {
    properties: {
        korean_name: {
            type: 'string',
            title: 'Korean Name'
        },
        english_name: {
            type: 'string',
            title: 'English Name'
        },
        birth_date: {
            type: 'string',
            format: 'date',
            title: 'Birth Date'
        },
        chinese_name: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Chinese Name'
        },
        resident_number: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Resident Number'
        },
        blessing_date: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Blessing Date'
        },
        appointment_date: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Appointment Date'
        },
        nationality: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Nationality',
            default: '대한민국'
        },
        organization: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Organization'
        },
        department: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Department'
        },
        position: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Position'
        },
        mobile_phone: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Mobile Phone'
        },
        extension: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Extension'
        },
        email: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email'
        },
        address: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Address'
        },
        remarks: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Remarks'
        },
        profile_update_date: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Profile Update Date'
        },
        resume_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Resume Id'
        }
    },
    type: 'object',
    required: ['korean_name', 'english_name', 'birth_date'],
    title: 'PersonalProfileCreate'
} as const;

export const PersonalProfileReadSchema = {
    properties: {
        korean_name: {
            type: 'string',
            title: 'Korean Name'
        },
        english_name: {
            type: 'string',
            title: 'English Name'
        },
        birth_date: {
            type: 'string',
            format: 'date',
            title: 'Birth Date'
        },
        chinese_name: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Chinese Name'
        },
        resident_number: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Resident Number'
        },
        blessing_date: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Blessing Date'
        },
        appointment_date: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Appointment Date'
        },
        nationality: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Nationality',
            default: '대한민국'
        },
        organization: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Organization'
        },
        department: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Department'
        },
        position: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Position'
        },
        mobile_phone: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Mobile Phone'
        },
        extension: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Extension'
        },
        email: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email'
        },
        address: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Address'
        },
        remarks: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Remarks'
        },
        profile_update_date: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Profile Update Date'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        resume_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Resume Id'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        },
        updated_at: {
            type: 'string',
            format: 'date-time',
            title: 'Updated At'
        }
    },
    type: 'object',
    required: ['korean_name', 'english_name', 'birth_date', 'id', 'created_at', 'updated_at'],
    title: 'PersonalProfileRead'
} as const;

export const ResumeCreateSchema = {
    properties: {
        resume_name: {
            type: 'string',
            title: 'Resume Name'
        },
        resume_version: {
            type: 'string',
            title: 'Resume Version',
            default: '1.0'
        },
        status: {
            type: 'string',
            title: 'Status',
            default: 'draft'
        },
        language: {
            type: 'string',
            title: 'Language',
            default: 'ko'
        },
        purpose: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Purpose'
        },
        notes: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Notes'
        },
        is_current: {
            type: 'boolean',
            title: 'Is Current',
            default: true
        },
        user_id: {
            type: 'string',
            format: 'uuid',
            title: 'User Id'
        },
        profile_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Profile Id'
        },
        created_by: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created By'
        },
        previous_version_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Previous Version Id'
        }
    },
    type: 'object',
    required: ['resume_name', 'user_id'],
    title: 'ResumeCreate'
} as const;

export const ResumeDetailSchema = {
    properties: {
        resume_name: {
            type: 'string',
            title: 'Resume Name'
        },
        resume_version: {
            type: 'string',
            title: 'Resume Version',
            default: '1.0'
        },
        status: {
            type: 'string',
            title: 'Status',
            default: 'draft'
        },
        language: {
            type: 'string',
            title: 'Language',
            default: 'ko'
        },
        purpose: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Purpose'
        },
        notes: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Notes'
        },
        is_current: {
            type: 'boolean',
            title: 'Is Current',
            default: true
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        user_id: {
            type: 'string',
            format: 'uuid',
            title: 'User Id'
        },
        profile_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Profile Id'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        },
        updated_at: {
            type: 'string',
            format: 'date-time',
            title: 'Updated At'
        },
        created_by: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created By'
        },
        previous_version_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Previous Version Id'
        },
        personal_profiles: {
            items: {
                '$ref': '#/components/schemas/PersonalProfileRead'
            },
            type: 'array',
            title: 'Personal Profiles'
        },
        education_history: {
            items: {
                '$ref': '#/components/schemas/EducationHistoryRead'
            },
            type: 'array',
            title: 'Education History'
        },
        family_members: {
            items: {
                '$ref': '#/components/schemas/FamilyMemberRead'
            },
            type: 'array',
            title: 'Family Members'
        },
        work_experience: {
            items: {
                '$ref': '#/components/schemas/WorkExperienceRead'
            },
            type: 'array',
            title: 'Work Experience'
        },
        organizational_activities: {
            items: {
                '$ref': '#/components/schemas/OrganizationalActivityRead'
            },
            type: 'array',
            title: 'Organizational Activities'
        },
        training_programs: {
            items: {
                '$ref': '#/components/schemas/TrainingProgramRead'
            },
            type: 'array',
            title: 'Training Programs'
        },
        certifications: {
            items: {
                '$ref': '#/components/schemas/CertificationRead'
            },
            type: 'array',
            title: 'Certifications'
        },
        awards: {
            items: {
                '$ref': '#/components/schemas/AwardRead'
            },
            type: 'array',
            title: 'Awards'
        },
        discipline_records: {
            items: {
                '$ref': '#/components/schemas/DisciplineRecordRead'
            },
            type: 'array',
            title: 'Discipline Records'
        },
        additional_remarks: {
            items: {
                '$ref': '#/components/schemas/AdditionalRemarkRead'
            },
            type: 'array',
            title: 'Additional Remarks'
        },
        sections: {
            items: {
                '$ref': '#/components/schemas/ResumeSectionRead'
            },
            type: 'array',
            title: 'Sections'
        }
    },
    type: 'object',
    required: ['resume_name', 'id', 'user_id', 'created_at', 'updated_at'],
    title: 'ResumeDetail'
} as const;

export const ResumeReadSchema = {
    properties: {
        resume_name: {
            type: 'string',
            title: 'Resume Name'
        },
        resume_version: {
            type: 'string',
            title: 'Resume Version',
            default: '1.0'
        },
        status: {
            type: 'string',
            title: 'Status',
            default: 'draft'
        },
        language: {
            type: 'string',
            title: 'Language',
            default: 'ko'
        },
        purpose: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Purpose'
        },
        notes: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Notes'
        },
        is_current: {
            type: 'boolean',
            title: 'Is Current',
            default: true
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        user_id: {
            type: 'string',
            format: 'uuid',
            title: 'User Id'
        },
        profile_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Profile Id'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        },
        updated_at: {
            type: 'string',
            format: 'date-time',
            title: 'Updated At'
        },
        created_by: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created By'
        },
        previous_version_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Previous Version Id'
        }
    },
    type: 'object',
    required: ['resume_name', 'id', 'user_id', 'created_at', 'updated_at'],
    title: 'ResumeRead'
} as const;

export const ResumeSectionCreateSchema = {
    properties: {
        section_type: {
            type: 'string',
            title: 'Section Type'
        },
        section_name: {
            type: 'string',
            title: 'Section Name'
        },
        display_order: {
            type: 'integer',
            title: 'Display Order',
            default: 0
        },
        is_included: {
            type: 'boolean',
            title: 'Is Included',
            default: true
        },
        resume_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Resume Id'
        }
    },
    type: 'object',
    required: ['section_type', 'section_name'],
    title: 'ResumeSectionCreate'
} as const;

export const ResumeSectionReadSchema = {
    properties: {
        section_type: {
            type: 'string',
            title: 'Section Type'
        },
        section_name: {
            type: 'string',
            title: 'Section Name'
        },
        display_order: {
            type: 'integer',
            title: 'Display Order',
            default: 0
        },
        is_included: {
            type: 'boolean',
            title: 'Is Included',
            default: true
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        resume_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Resume Id'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['section_type', 'section_name', 'id', 'created_at'],
    title: 'ResumeSectionRead'
} as const;

export const ResumeSummarySchema = {
    properties: {
        total_records: {
            type: 'integer',
            minimum: 0,
            title: 'Total Records'
        }
    },
    type: 'object',
    required: ['total_records'],
    title: 'ResumeSummary'
} as const;

export const RoleReadSchema = {
    properties: {
        name: {
            type: 'string',
            enum: ['admin', 'manager', 'user'],
            title: 'Name',
            description: 'Name of the role within the system.'
        },
        id: {
            type: 'integer',
            title: 'Id'
        }
    },
    type: 'object',
    required: ['name', 'id'],
    title: 'RoleRead'
} as const;

export const TrainingProgramCreateSchema = {
    properties: {
        program_name: {
            type: 'string',
            title: 'Program Name'
        },
        start_date: {
            type: 'string',
            format: 'date',
            title: 'Start Date'
        },
        end_date: {
            type: 'string',
            format: 'date',
            title: 'End Date'
        },
        organizing_institution: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Organizing Institution'
        },
        completion_status: {
            type: 'boolean',
            title: 'Completion Status',
            default: false
        },
        display_order: {
            type: 'integer',
            title: 'Display Order',
            default: 0
        },
        resume_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Resume Id'
        }
    },
    type: 'object',
    required: ['program_name', 'start_date', 'end_date'],
    title: 'TrainingProgramCreate'
} as const;

export const TrainingProgramReadSchema = {
    properties: {
        program_name: {
            type: 'string',
            title: 'Program Name'
        },
        start_date: {
            type: 'string',
            format: 'date',
            title: 'Start Date'
        },
        end_date: {
            type: 'string',
            format: 'date',
            title: 'End Date'
        },
        organizing_institution: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Organizing Institution'
        },
        completion_status: {
            type: 'boolean',
            title: 'Completion Status',
            default: false
        },
        display_order: {
            type: 'integer',
            title: 'Display Order',
            default: 0
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        resume_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Resume Id'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['program_name', 'start_date', 'end_date', 'id', 'created_at'],
    title: 'TrainingProgramRead'
} as const;

export const UserCreateSchema = {
    properties: {
        username: {
            type: 'string',
            maxLength: 50,
            minLength: 3,
            title: 'Username'
        },
        name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 100
                },
                {
                    type: 'null'
                }
            ],
            title: 'Name'
        },
        profile_photo_url: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Profile Photo Url'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        email: {
            type: 'string',
            format: 'email',
            title: 'Email'
        },
        password: {
            anyOf: [
                {
                    type: 'string',
                    minLength: 8
                },
                {
                    type: 'null'
                }
            ],
            title: 'Password'
        },
        google_id: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Google Id'
        },
        google_refresh_token: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Google Refresh Token'
        },
        google_access_token: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Google Access Token'
        },
        google_auth_active: {
            type: 'boolean',
            title: 'Google Auth Active',
            default: false
        },
        role_name: {
            anyOf: [
                {
                    type: 'string',
                    enum: ['admin', 'manager', 'user']
                },
                {
                    type: 'null'
                }
            ],
            title: 'Role Name',
            description: 'Optional role override when creating privileged users.'
        }
    },
    type: 'object',
    required: ['username', 'email'],
    title: 'UserCreate'
} as const;

export const UserReadSchema = {
    properties: {
        username: {
            type: 'string',
            maxLength: 50,
            minLength: 3,
            title: 'Username'
        },
        name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 100
                },
                {
                    type: 'null'
                }
            ],
            title: 'Name'
        },
        profile_photo_url: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Profile Photo Url'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        email: {
            type: 'string',
            format: 'email',
            title: 'Email'
        },
        role: {
            '$ref': '#/components/schemas/RoleRead'
        },
        google_id: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Google Id'
        },
        google_auth_active: {
            type: 'boolean',
            title: 'Google Auth Active'
        },
        last_login: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Last Login'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        },
        updated_at: {
            type: 'string',
            format: 'date-time',
            title: 'Updated At'
        },
        is_deleted: {
            type: 'boolean',
            title: 'Is Deleted'
        }
    },
    type: 'object',
    required: ['username', 'id', 'email', 'role', 'google_auth_active', 'created_at', 'updated_at', 'is_deleted'],
    title: 'UserRead'
} as const;

export const UserSessionReadSchema = {
    properties: {
        session_token: {
            type: 'string',
            title: 'Session Token'
        },
        refresh_token: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Refresh Token'
        },
        expires_at: {
            type: 'string',
            format: 'date-time',
            title: 'Expires At'
        },
        user_agent: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'User Agent'
        },
        ip_address: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Ip Address'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        user_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'User Id'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['session_token', 'expires_at', 'id', 'created_at'],
    title: 'UserSessionRead'
} as const;

export const UserUpdateSchema = {
    properties: {
        email: {
            anyOf: [
                {
                    type: 'string',
                    format: 'email'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email'
        },
        username: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 50,
                    minLength: 3
                },
                {
                    type: 'null'
                }
            ],
            title: 'Username'
        },
        name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 100
                },
                {
                    type: 'null'
                }
            ],
            title: 'Name'
        },
        profile_photo_url: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Profile Photo Url'
        },
        is_active: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Is Active'
        },
        password: {
            anyOf: [
                {
                    type: 'string',
                    minLength: 8
                },
                {
                    type: 'null'
                }
            ],
            title: 'Password'
        },
        google_id: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Google Id'
        },
        google_refresh_token: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Google Refresh Token'
        },
        google_access_token: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Google Access Token'
        },
        google_auth_active: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Google Auth Active'
        },
        role_name: {
            anyOf: [
                {
                    type: 'string',
                    enum: ['admin', 'manager', 'user']
                },
                {
                    type: 'null'
                }
            ],
            title: 'Role Name'
        },
        is_deleted: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Is Deleted'
        }
    },
    type: 'object',
    title: 'UserUpdate'
} as const;

export const ValidationErrorSchema = {
    properties: {
        loc: {
            items: {
                anyOf: [
                    {
                        type: 'string'
                    },
                    {
                        type: 'integer'
                    }
                ]
            },
            type: 'array',
            title: 'Location'
        },
        msg: {
            type: 'string',
            title: 'Message'
        },
        type: {
            type: 'string',
            title: 'Error Type'
        }
    },
    type: 'object',
    required: ['loc', 'msg', 'type'],
    title: 'ValidationError'
} as const;

export const WorkExperienceCreateSchema = {
    properties: {
        start_date: {
            type: 'string',
            format: 'date',
            title: 'Start Date'
        },
        end_date: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date'
                },
                {
                    type: 'null'
                }
            ],
            title: 'End Date'
        },
        organization: {
            type: 'string',
            title: 'Organization'
        },
        department: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Department'
        },
        position: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Position'
        },
        responsibilities: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Responsibilities'
        },
        current_job: {
            type: 'boolean',
            title: 'Current Job',
            default: false
        },
        display_order: {
            type: 'integer',
            title: 'Display Order',
            default: 0
        },
        resume_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Resume Id'
        }
    },
    type: 'object',
    required: ['start_date', 'organization'],
    title: 'WorkExperienceCreate'
} as const;

export const WorkExperienceReadSchema = {
    properties: {
        start_date: {
            type: 'string',
            format: 'date',
            title: 'Start Date'
        },
        end_date: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date'
                },
                {
                    type: 'null'
                }
            ],
            title: 'End Date'
        },
        organization: {
            type: 'string',
            title: 'Organization'
        },
        department: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Department'
        },
        position: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Position'
        },
        responsibilities: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Responsibilities'
        },
        current_job: {
            type: 'boolean',
            title: 'Current Job',
            default: false
        },
        display_order: {
            type: 'integer',
            title: 'Display Order',
            default: 0
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        resume_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Resume Id'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['start_date', 'organization', 'id', 'created_at'],
    title: 'WorkExperienceRead'
} as const;
