// This file is auto-generated by @hey-api/openapi-ts

import type { AuthActivateGoogleLoginResponse, AuthCreateUserResponse, AuthDeactivateGoogleLoginResponse, AuthGetUserResponse, AuthListUsersResponse, AuthLoginResponse, AuthResetPasswordResponse, AuthUpdateGoogleTokensResponse, AuthUpdateUserResponse, ResumesCreateActivityResponse, ResumesCreateAwardResponse, ResumesCreateCertificationResponse, ResumesCreateDisciplineRecordResponse, ResumesCreateEducationResponse, ResumesCreateFamilyMemberResponse, ResumesCreateProfileResponse, ResumesCreateRemarkResponse, ResumesCreateResumeResponse, ResumesCreateSectionResponse, ResumesCreateTrainingResponse, ResumesCreateWorkExperienceResponse, ResumesGetFullResumeResponse, ResumesGetResumeResponse, ResumesListActivitiesResponse, ResumesListAwardsResponse, ResumesListCertificationsResponse, ResumesListDisciplineResponse, ResumesListEducationResponse, ResumesListEmailTokensResponse, ResumesListFamilyResponse, ResumesListProfilesResponse, ResumesListRemarksResponse, ResumesListResumesResponse, ResumesListSectionsResponse, ResumesListTrainingResponse, ResumesListUserSessionsResponse, ResumesListWorkResponse, ResumesUpdateResumeResponse, ResumesUpdateSectionResponse } from './types.gen';

const loginResponseSchemaResponseTransformer = (data: any) => {
    data.user = userReadSchemaResponseTransformer(data.user);
    return data;
};

const userReadSchemaResponseTransformer = (data: any) => {
    if (data.last_login) {
        data.last_login = new Date(data.last_login);
    }
    data.created_at = new Date(data.created_at);
    data.updated_at = new Date(data.updated_at);
    return data;
};

export const authLoginResponseTransformer = async (data: any): Promise<AuthLoginResponse> => {
    data = loginResponseSchemaResponseTransformer(data);
    return data;
};

export const authResetPasswordResponseTransformer = async (data: any): Promise<AuthResetPasswordResponse> => {
    data = userReadSchemaResponseTransformer(data);
    return data;
};

export const authListUsersResponseTransformer = async (data: any): Promise<AuthListUsersResponse> => {
    data = data.map((item: any) => {
        return userReadSchemaResponseTransformer(item);
    });
    return data;
};

export const authCreateUserResponseTransformer = async (data: any): Promise<AuthCreateUserResponse> => {
    data = userReadSchemaResponseTransformer(data);
    return data;
};

export const authGetUserResponseTransformer = async (data: any): Promise<AuthGetUserResponse> => {
    data = userReadSchemaResponseTransformer(data);
    return data;
};

export const authUpdateUserResponseTransformer = async (data: any): Promise<AuthUpdateUserResponse> => {
    data = userReadSchemaResponseTransformer(data);
    return data;
};

export const authActivateGoogleLoginResponseTransformer = async (data: any): Promise<AuthActivateGoogleLoginResponse> => {
    data = userReadSchemaResponseTransformer(data);
    return data;
};

export const authUpdateGoogleTokensResponseTransformer = async (data: any): Promise<AuthUpdateGoogleTokensResponse> => {
    data = userReadSchemaResponseTransformer(data);
    return data;
};

export const authDeactivateGoogleLoginResponseTransformer = async (data: any): Promise<AuthDeactivateGoogleLoginResponse> => {
    data = userReadSchemaResponseTransformer(data);
    return data;
};

const resumeReadSchemaResponseTransformer = (data: any) => {
    data.created_at = new Date(data.created_at);
    data.updated_at = new Date(data.updated_at);
    return data;
};

export const resumesListResumesResponseTransformer = async (data: any): Promise<ResumesListResumesResponse> => {
    data = data.map((item: any) => {
        return resumeReadSchemaResponseTransformer(item);
    });
    return data;
};

export const resumesCreateResumeResponseTransformer = async (data: any): Promise<ResumesCreateResumeResponse> => {
    data = resumeReadSchemaResponseTransformer(data);
    return data;
};

export const resumesGetResumeResponseTransformer = async (data: any): Promise<ResumesGetResumeResponse> => {
    data = resumeReadSchemaResponseTransformer(data);
    return data;
};

export const resumesUpdateResumeResponseTransformer = async (data: any): Promise<ResumesUpdateResumeResponse> => {
    data = resumeReadSchemaResponseTransformer(data);
    return data;
};

const resumeDetailSchemaResponseTransformer = (data: any) => {
    data.created_at = new Date(data.created_at);
    data.updated_at = new Date(data.updated_at);
    if (data.personal_profiles) {
        data.personal_profiles = data.personal_profiles.map((item: any) => {
            return personalProfileReadSchemaResponseTransformer(item);
        });
    }
    if (data.education_history) {
        data.education_history = data.education_history.map((item: any) => {
            return educationHistoryReadSchemaResponseTransformer(item);
        });
    }
    if (data.family_members) {
        data.family_members = data.family_members.map((item: any) => {
            return familyMemberReadSchemaResponseTransformer(item);
        });
    }
    if (data.work_experience) {
        data.work_experience = data.work_experience.map((item: any) => {
            return workExperienceReadSchemaResponseTransformer(item);
        });
    }
    if (data.organizational_activities) {
        data.organizational_activities = data.organizational_activities.map((item: any) => {
            return organizationalActivityReadSchemaResponseTransformer(item);
        });
    }
    if (data.training_programs) {
        data.training_programs = data.training_programs.map((item: any) => {
            return trainingProgramReadSchemaResponseTransformer(item);
        });
    }
    if (data.certifications) {
        data.certifications = data.certifications.map((item: any) => {
            return certificationReadSchemaResponseTransformer(item);
        });
    }
    if (data.awards) {
        data.awards = data.awards.map((item: any) => {
            return awardReadSchemaResponseTransformer(item);
        });
    }
    if (data.discipline_records) {
        data.discipline_records = data.discipline_records.map((item: any) => {
            return disciplineRecordReadSchemaResponseTransformer(item);
        });
    }
    if (data.additional_remarks) {
        data.additional_remarks = data.additional_remarks.map((item: any) => {
            return additionalRemarkReadSchemaResponseTransformer(item);
        });
    }
    if (data.sections) {
        data.sections = data.sections.map((item: any) => {
            return resumeSectionReadSchemaResponseTransformer(item);
        });
    }
    return data;
};

const personalProfileReadSchemaResponseTransformer = (data: any) => {
    data.birth_date = new Date(data.birth_date);
    if (data.blessing_date) {
        data.blessing_date = new Date(data.blessing_date);
    }
    if (data.appointment_date) {
        data.appointment_date = new Date(data.appointment_date);
    }
    if (data.profile_update_date) {
        data.profile_update_date = new Date(data.profile_update_date);
    }
    data.created_at = new Date(data.created_at);
    data.updated_at = new Date(data.updated_at);
    return data;
};

const educationHistoryReadSchemaResponseTransformer = (data: any) => {
    data.start_date = new Date(data.start_date);
    data.end_date = new Date(data.end_date);
    data.created_at = new Date(data.created_at);
    return data;
};

const familyMemberReadSchemaResponseTransformer = (data: any) => {
    if (data.birth_date) {
        data.birth_date = new Date(data.birth_date);
    }
    data.created_at = new Date(data.created_at);
    return data;
};

const workExperienceReadSchemaResponseTransformer = (data: any) => {
    data.start_date = new Date(data.start_date);
    if (data.end_date) {
        data.end_date = new Date(data.end_date);
    }
    data.created_at = new Date(data.created_at);
    return data;
};

const organizationalActivityReadSchemaResponseTransformer = (data: any) => {
    data.start_date = new Date(data.start_date);
    if (data.end_date) {
        data.end_date = new Date(data.end_date);
    }
    data.created_at = new Date(data.created_at);
    return data;
};

const trainingProgramReadSchemaResponseTransformer = (data: any) => {
    data.start_date = new Date(data.start_date);
    data.end_date = new Date(data.end_date);
    data.created_at = new Date(data.created_at);
    return data;
};

const certificationReadSchemaResponseTransformer = (data: any) => {
    data.acquisition_date = new Date(data.acquisition_date);
    data.created_at = new Date(data.created_at);
    return data;
};

const awardReadSchemaResponseTransformer = (data: any) => {
    data.award_date = new Date(data.award_date);
    data.created_at = new Date(data.created_at);
    return data;
};

const disciplineRecordReadSchemaResponseTransformer = (data: any) => {
    data.record_date = new Date(data.record_date);
    data.created_at = new Date(data.created_at);
    return data;
};

const additionalRemarkReadSchemaResponseTransformer = (data: any) => {
    data.registration_date = new Date(data.registration_date);
    data.created_at = new Date(data.created_at);
    return data;
};

const resumeSectionReadSchemaResponseTransformer = (data: any) => {
    data.created_at = new Date(data.created_at);
    return data;
};

export const resumesGetFullResumeResponseTransformer = async (data: any): Promise<ResumesGetFullResumeResponse> => {
    data = resumeDetailSchemaResponseTransformer(data);
    return data;
};

export const resumesListProfilesResponseTransformer = async (data: any): Promise<ResumesListProfilesResponse> => {
    data = data.map((item: any) => {
        return personalProfileReadSchemaResponseTransformer(item);
    });
    return data;
};

export const resumesCreateProfileResponseTransformer = async (data: any): Promise<ResumesCreateProfileResponse> => {
    data = personalProfileReadSchemaResponseTransformer(data);
    return data;
};

export const resumesListEducationResponseTransformer = async (data: any): Promise<ResumesListEducationResponse> => {
    data = data.map((item: any) => {
        return educationHistoryReadSchemaResponseTransformer(item);
    });
    return data;
};

export const resumesCreateEducationResponseTransformer = async (data: any): Promise<ResumesCreateEducationResponse> => {
    data = educationHistoryReadSchemaResponseTransformer(data);
    return data;
};

export const resumesListFamilyResponseTransformer = async (data: any): Promise<ResumesListFamilyResponse> => {
    data = data.map((item: any) => {
        return familyMemberReadSchemaResponseTransformer(item);
    });
    return data;
};

export const resumesCreateFamilyMemberResponseTransformer = async (data: any): Promise<ResumesCreateFamilyMemberResponse> => {
    data = familyMemberReadSchemaResponseTransformer(data);
    return data;
};

export const resumesListWorkResponseTransformer = async (data: any): Promise<ResumesListWorkResponse> => {
    data = data.map((item: any) => {
        return workExperienceReadSchemaResponseTransformer(item);
    });
    return data;
};

export const resumesCreateWorkExperienceResponseTransformer = async (data: any): Promise<ResumesCreateWorkExperienceResponse> => {
    data = workExperienceReadSchemaResponseTransformer(data);
    return data;
};

export const resumesListActivitiesResponseTransformer = async (data: any): Promise<ResumesListActivitiesResponse> => {
    data = data.map((item: any) => {
        return organizationalActivityReadSchemaResponseTransformer(item);
    });
    return data;
};

export const resumesCreateActivityResponseTransformer = async (data: any): Promise<ResumesCreateActivityResponse> => {
    data = organizationalActivityReadSchemaResponseTransformer(data);
    return data;
};

export const resumesListTrainingResponseTransformer = async (data: any): Promise<ResumesListTrainingResponse> => {
    data = data.map((item: any) => {
        return trainingProgramReadSchemaResponseTransformer(item);
    });
    return data;
};

export const resumesCreateTrainingResponseTransformer = async (data: any): Promise<ResumesCreateTrainingResponse> => {
    data = trainingProgramReadSchemaResponseTransformer(data);
    return data;
};

export const resumesListCertificationsResponseTransformer = async (data: any): Promise<ResumesListCertificationsResponse> => {
    data = data.map((item: any) => {
        return certificationReadSchemaResponseTransformer(item);
    });
    return data;
};

export const resumesCreateCertificationResponseTransformer = async (data: any): Promise<ResumesCreateCertificationResponse> => {
    data = certificationReadSchemaResponseTransformer(data);
    return data;
};

export const resumesListAwardsResponseTransformer = async (data: any): Promise<ResumesListAwardsResponse> => {
    data = data.map((item: any) => {
        return awardReadSchemaResponseTransformer(item);
    });
    return data;
};

export const resumesCreateAwardResponseTransformer = async (data: any): Promise<ResumesCreateAwardResponse> => {
    data = awardReadSchemaResponseTransformer(data);
    return data;
};

export const resumesListDisciplineResponseTransformer = async (data: any): Promise<ResumesListDisciplineResponse> => {
    data = data.map((item: any) => {
        return disciplineRecordReadSchemaResponseTransformer(item);
    });
    return data;
};

export const resumesCreateDisciplineRecordResponseTransformer = async (data: any): Promise<ResumesCreateDisciplineRecordResponse> => {
    data = disciplineRecordReadSchemaResponseTransformer(data);
    return data;
};

export const resumesListRemarksResponseTransformer = async (data: any): Promise<ResumesListRemarksResponse> => {
    data = data.map((item: any) => {
        return additionalRemarkReadSchemaResponseTransformer(item);
    });
    return data;
};

export const resumesCreateRemarkResponseTransformer = async (data: any): Promise<ResumesCreateRemarkResponse> => {
    data = additionalRemarkReadSchemaResponseTransformer(data);
    return data;
};

export const resumesListSectionsResponseTransformer = async (data: any): Promise<ResumesListSectionsResponse> => {
    data = data.map((item: any) => {
        return resumeSectionReadSchemaResponseTransformer(item);
    });
    return data;
};

export const resumesCreateSectionResponseTransformer = async (data: any): Promise<ResumesCreateSectionResponse> => {
    data = resumeSectionReadSchemaResponseTransformer(data);
    return data;
};

export const resumesUpdateSectionResponseTransformer = async (data: any): Promise<ResumesUpdateSectionResponse> => {
    data = resumeSectionReadSchemaResponseTransformer(data);
    return data;
};

const userSessionReadSchemaResponseTransformer = (data: any) => {
    data.expires_at = new Date(data.expires_at);
    data.created_at = new Date(data.created_at);
    return data;
};

export const resumesListUserSessionsResponseTransformer = async (data: any): Promise<ResumesListUserSessionsResponse> => {
    data = data.map((item: any) => {
        return userSessionReadSchemaResponseTransformer(item);
    });
    return data;
};

const emailVerificationTokenReadSchemaResponseTransformer = (data: any) => {
    data.expires_at = new Date(data.expires_at);
    if (data.used_at) {
        data.used_at = new Date(data.used_at);
    }
    data.created_at = new Date(data.created_at);
    return data;
};

export const resumesListEmailTokensResponseTransformer = async (data: any): Promise<ResumesListEmailTokensResponse> => {
    data = data.map((item: any) => {
        return emailVerificationTokenReadSchemaResponseTransformer(item);
    });
    return data;
};
