// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

/**
 * AdditionalRemarkCreate
 */
export type AdditionalRemarkCreate = {
    /**
     * Registration Date
     */
    registration_date: Date;
    /**
     * Content
     */
    content?: string | null;
    /**
     * Display Order
     */
    display_order?: number;
    /**
     * Resume Id
     */
    resume_id?: string | null;
};

/**
 * AdditionalRemarkRead
 */
export type AdditionalRemarkRead = {
    /**
     * Registration Date
     */
    registration_date: Date;
    /**
     * Content
     */
    content?: string | null;
    /**
     * Display Order
     */
    display_order?: number;
    /**
     * Id
     */
    id: string;
    /**
     * Resume Id
     */
    resume_id?: string | null;
    /**
     * Created At
     */
    created_at: Date;
};

/**
 * AuthStatus
 */
export type AuthStatus = {
    /**
     * Healthy
     */
    healthy: boolean;
};

/**
 * AwardCreate
 */
export type AwardCreate = {
    /**
     * Award Date
     */
    award_date: Date;
    /**
     * Category
     */
    category?: string | null;
    /**
     * Details
     */
    details?: string | null;
    /**
     * Awarding Institution
     */
    awarding_institution?: string | null;
    /**
     * Display Order
     */
    display_order?: number;
    /**
     * Resume Id
     */
    resume_id?: string | null;
};

/**
 * AwardRead
 */
export type AwardRead = {
    /**
     * Award Date
     */
    award_date: Date;
    /**
     * Category
     */
    category?: string | null;
    /**
     * Details
     */
    details?: string | null;
    /**
     * Awarding Institution
     */
    awarding_institution?: string | null;
    /**
     * Display Order
     */
    display_order?: number;
    /**
     * Id
     */
    id: string;
    /**
     * Resume Id
     */
    resume_id?: string | null;
    /**
     * Created At
     */
    created_at: Date;
};

/**
 * CertificationCreate
 */
export type CertificationCreate = {
    /**
     * Acquisition Date
     */
    acquisition_date: Date;
    /**
     * Certification Name
     */
    certification_name: string;
    /**
     * Remarks
     */
    remarks?: string | null;
    /**
     * Display Order
     */
    display_order?: number;
    /**
     * Resume Id
     */
    resume_id?: string | null;
};

/**
 * CertificationRead
 */
export type CertificationRead = {
    /**
     * Acquisition Date
     */
    acquisition_date: Date;
    /**
     * Certification Name
     */
    certification_name: string;
    /**
     * Remarks
     */
    remarks?: string | null;
    /**
     * Display Order
     */
    display_order?: number;
    /**
     * Id
     */
    id: string;
    /**
     * Resume Id
     */
    resume_id?: string | null;
    /**
     * Created At
     */
    created_at: Date;
};

/**
 * DisciplineRecordCreate
 */
export type DisciplineRecordCreate = {
    /**
     * Record Date
     */
    record_date: Date;
    /**
     * Type
     */
    type?: string | null;
    /**
     * Reason
     */
    reason?: string | null;
    /**
     * Display Order
     */
    display_order?: number;
    /**
     * Resume Id
     */
    resume_id?: string | null;
};

/**
 * DisciplineRecordRead
 */
export type DisciplineRecordRead = {
    /**
     * Record Date
     */
    record_date: Date;
    /**
     * Type
     */
    type?: string | null;
    /**
     * Reason
     */
    reason?: string | null;
    /**
     * Display Order
     */
    display_order?: number;
    /**
     * Id
     */
    id: string;
    /**
     * Resume Id
     */
    resume_id?: string | null;
    /**
     * Created At
     */
    created_at: Date;
};

/**
 * EducationHistoryCreate
 */
export type EducationHistoryCreate = {
    /**
     * Start Date
     */
    start_date: Date;
    /**
     * End Date
     */
    end_date: Date;
    /**
     * Institution
     */
    institution: string;
    /**
     * Major
     */
    major?: string | null;
    /**
     * Graduation Type
     */
    graduation_type?: string | null;
    /**
     * Degree
     */
    degree?: string | null;
    /**
     * Display Order
     */
    display_order?: number;
    /**
     * Resume Id
     */
    resume_id?: string | null;
};

/**
 * EducationHistoryRead
 */
export type EducationHistoryRead = {
    /**
     * Start Date
     */
    start_date: Date;
    /**
     * End Date
     */
    end_date: Date;
    /**
     * Institution
     */
    institution: string;
    /**
     * Major
     */
    major?: string | null;
    /**
     * Graduation Type
     */
    graduation_type?: string | null;
    /**
     * Degree
     */
    degree?: string | null;
    /**
     * Display Order
     */
    display_order?: number;
    /**
     * Id
     */
    id: string;
    /**
     * Resume Id
     */
    resume_id?: string | null;
    /**
     * Created At
     */
    created_at: Date;
};

/**
 * EmailVerificationTokenRead
 */
export type EmailVerificationTokenRead = {
    /**
     * Token
     */
    token: string;
    /**
     * Expires At
     */
    expires_at: Date;
    /**
     * Used At
     */
    used_at?: Date | null;
    /**
     * Id
     */
    id: string;
    /**
     * User Id
     */
    user_id?: string | null;
    /**
     * Created At
     */
    created_at: Date;
};

/**
 * FamilyMemberCreate
 */
export type FamilyMemberCreate = {
    /**
     * Relationship
     */
    relationship: string;
    /**
     * Name
     */
    name: string;
    /**
     * Birth Date
     */
    birth_date?: Date | null;
    /**
     * Blessed
     */
    blessed?: boolean;
    /**
     * Remarks
     */
    remarks?: string | null;
    /**
     * Display Order
     */
    display_order?: number;
    /**
     * Resume Id
     */
    resume_id?: string | null;
};

/**
 * FamilyMemberRead
 */
export type FamilyMemberRead = {
    /**
     * Relationship
     */
    relationship: string;
    /**
     * Name
     */
    name: string;
    /**
     * Birth Date
     */
    birth_date?: Date | null;
    /**
     * Blessed
     */
    blessed?: boolean;
    /**
     * Remarks
     */
    remarks?: string | null;
    /**
     * Display Order
     */
    display_order?: number;
    /**
     * Id
     */
    id: string;
    /**
     * Resume Id
     */
    resume_id?: string | null;
    /**
     * Created At
     */
    created_at: Date;
};

/**
 * GoogleAuthActivate
 */
export type GoogleAuthActivate = {
    /**
     * Google Id
     */
    google_id: string;
    /**
     * Google Refresh Token
     */
    google_refresh_token?: string | null;
    /**
     * Google Access Token
     */
    google_access_token?: string | null;
};

/**
 * GoogleTokenUpdate
 */
export type GoogleTokenUpdate = {
    /**
     * Google Refresh Token
     */
    google_refresh_token: string;
    /**
     * Google Access Token
     */
    google_access_token: string;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * LoginRequest
 */
export type LoginRequest = {
    /**
     * Identifier
     */
    identifier: string;
    /**
     * Password
     */
    password: string;
};

/**
 * LoginResponse
 */
export type LoginResponse = {
    /**
     * Access Token
     */
    access_token: string;
    /**
     * Token Type
     */
    token_type?: 'bearer';
    /**
     * Expires In
     */
    expires_in: number;
    user: UserRead;
};

/**
 * OrganizationalActivityCreate
 */
export type OrganizationalActivityCreate = {
    /**
     * Start Date
     */
    start_date: Date;
    /**
     * End Date
     */
    end_date?: Date | null;
    /**
     * Organization Name
     */
    organization_name: string;
    /**
     * Position
     */
    position?: string | null;
    /**
     * Main Role
     */
    main_role?: string | null;
    /**
     * Display Order
     */
    display_order?: number;
    /**
     * Resume Id
     */
    resume_id?: string | null;
};

/**
 * OrganizationalActivityRead
 */
export type OrganizationalActivityRead = {
    /**
     * Start Date
     */
    start_date: Date;
    /**
     * End Date
     */
    end_date?: Date | null;
    /**
     * Organization Name
     */
    organization_name: string;
    /**
     * Position
     */
    position?: string | null;
    /**
     * Main Role
     */
    main_role?: string | null;
    /**
     * Display Order
     */
    display_order?: number;
    /**
     * Id
     */
    id: string;
    /**
     * Resume Id
     */
    resume_id?: string | null;
    /**
     * Created At
     */
    created_at: Date;
};

/**
 * PasswordResetConfirm
 */
export type PasswordResetConfirm = {
    /**
     * Token
     */
    token: string;
    /**
     * New Password
     */
    new_password: string;
};

/**
 * PasswordResetRequest
 */
export type PasswordResetRequest = {
    /**
     * Identifier
     *
     * Username, email, or user ID for the account.
     */
    identifier: string;
};

/**
 * PasswordResetToken
 */
export type PasswordResetToken = {
    /**
     * Token
     */
    token: string;
};

/**
 * PersonalProfileCreate
 */
export type PersonalProfileCreate = {
    /**
     * Korean Name
     */
    korean_name: string;
    /**
     * English Name
     */
    english_name: string;
    /**
     * Birth Date
     */
    birth_date: Date;
    /**
     * Chinese Name
     */
    chinese_name?: string | null;
    /**
     * Resident Number
     */
    resident_number?: string | null;
    /**
     * Blessing Date
     */
    blessing_date?: Date | null;
    /**
     * Appointment Date
     */
    appointment_date?: Date | null;
    /**
     * Nationality
     */
    nationality?: string | null;
    /**
     * Organization
     */
    organization?: string | null;
    /**
     * Department
     */
    department?: string | null;
    /**
     * Position
     */
    position?: string | null;
    /**
     * Mobile Phone
     */
    mobile_phone?: string | null;
    /**
     * Extension
     */
    extension?: string | null;
    /**
     * Email
     */
    email?: string | null;
    /**
     * Address
     */
    address?: string | null;
    /**
     * Remarks
     */
    remarks?: string | null;
    /**
     * Profile Update Date
     */
    profile_update_date?: Date | null;
    /**
     * Resume Id
     */
    resume_id?: string | null;
};

/**
 * PersonalProfileRead
 */
export type PersonalProfileRead = {
    /**
     * Korean Name
     */
    korean_name: string;
    /**
     * English Name
     */
    english_name: string;
    /**
     * Birth Date
     */
    birth_date: Date;
    /**
     * Chinese Name
     */
    chinese_name?: string | null;
    /**
     * Resident Number
     */
    resident_number?: string | null;
    /**
     * Blessing Date
     */
    blessing_date?: Date | null;
    /**
     * Appointment Date
     */
    appointment_date?: Date | null;
    /**
     * Nationality
     */
    nationality?: string | null;
    /**
     * Organization
     */
    organization?: string | null;
    /**
     * Department
     */
    department?: string | null;
    /**
     * Position
     */
    position?: string | null;
    /**
     * Mobile Phone
     */
    mobile_phone?: string | null;
    /**
     * Extension
     */
    extension?: string | null;
    /**
     * Email
     */
    email?: string | null;
    /**
     * Address
     */
    address?: string | null;
    /**
     * Remarks
     */
    remarks?: string | null;
    /**
     * Profile Update Date
     */
    profile_update_date?: Date | null;
    /**
     * Id
     */
    id: string;
    /**
     * Resume Id
     */
    resume_id?: string | null;
    /**
     * Created At
     */
    created_at: Date;
    /**
     * Updated At
     */
    updated_at: Date;
};

/**
 * ResumeCreate
 */
export type ResumeCreate = {
    /**
     * Resume Name
     */
    resume_name: string;
    /**
     * Resume Version
     */
    resume_version?: string;
    /**
     * Status
     */
    status?: string;
    /**
     * Language
     */
    language?: string;
    /**
     * Purpose
     */
    purpose?: string | null;
    /**
     * Notes
     */
    notes?: string | null;
    /**
     * Is Current
     */
    is_current?: boolean;
    /**
     * User Id
     */
    user_id: string;
    /**
     * Profile Id
     */
    profile_id?: string | null;
    /**
     * Created By
     */
    created_by?: string | null;
    /**
     * Previous Version Id
     */
    previous_version_id?: string | null;
};

/**
 * ResumeDetail
 */
export type ResumeDetail = {
    /**
     * Resume Name
     */
    resume_name: string;
    /**
     * Resume Version
     */
    resume_version?: string;
    /**
     * Status
     */
    status?: string;
    /**
     * Language
     */
    language?: string;
    /**
     * Purpose
     */
    purpose?: string | null;
    /**
     * Notes
     */
    notes?: string | null;
    /**
     * Is Current
     */
    is_current?: boolean;
    /**
     * Id
     */
    id: string;
    /**
     * User Id
     */
    user_id: string;
    /**
     * Profile Id
     */
    profile_id?: string | null;
    /**
     * Created At
     */
    created_at: Date;
    /**
     * Updated At
     */
    updated_at: Date;
    /**
     * Created By
     */
    created_by?: string | null;
    /**
     * Previous Version Id
     */
    previous_version_id?: string | null;
    /**
     * Personal Profiles
     */
    personal_profiles?: Array<PersonalProfileRead>;
    /**
     * Education History
     */
    education_history?: Array<EducationHistoryRead>;
    /**
     * Family Members
     */
    family_members?: Array<FamilyMemberRead>;
    /**
     * Work Experience
     */
    work_experience?: Array<WorkExperienceRead>;
    /**
     * Organizational Activities
     */
    organizational_activities?: Array<OrganizationalActivityRead>;
    /**
     * Training Programs
     */
    training_programs?: Array<TrainingProgramRead>;
    /**
     * Certifications
     */
    certifications?: Array<CertificationRead>;
    /**
     * Awards
     */
    awards?: Array<AwardRead>;
    /**
     * Discipline Records
     */
    discipline_records?: Array<DisciplineRecordRead>;
    /**
     * Additional Remarks
     */
    additional_remarks?: Array<AdditionalRemarkRead>;
    /**
     * Sections
     */
    sections?: Array<ResumeSectionRead>;
};

/**
 * ResumeRead
 */
export type ResumeRead = {
    /**
     * Resume Name
     */
    resume_name: string;
    /**
     * Resume Version
     */
    resume_version?: string;
    /**
     * Status
     */
    status?: string;
    /**
     * Language
     */
    language?: string;
    /**
     * Purpose
     */
    purpose?: string | null;
    /**
     * Notes
     */
    notes?: string | null;
    /**
     * Is Current
     */
    is_current?: boolean;
    /**
     * Id
     */
    id: string;
    /**
     * User Id
     */
    user_id: string;
    /**
     * Profile Id
     */
    profile_id?: string | null;
    /**
     * Created At
     */
    created_at: Date;
    /**
     * Updated At
     */
    updated_at: Date;
    /**
     * Created By
     */
    created_by?: string | null;
    /**
     * Previous Version Id
     */
    previous_version_id?: string | null;
};

/**
 * ResumeSectionCreate
 */
export type ResumeSectionCreate = {
    /**
     * Section Type
     */
    section_type: string;
    /**
     * Section Name
     */
    section_name: string;
    /**
     * Display Order
     */
    display_order?: number;
    /**
     * Is Included
     */
    is_included?: boolean;
    /**
     * Resume Id
     */
    resume_id?: string | null;
};

/**
 * ResumeSectionRead
 */
export type ResumeSectionRead = {
    /**
     * Section Type
     */
    section_type: string;
    /**
     * Section Name
     */
    section_name: string;
    /**
     * Display Order
     */
    display_order?: number;
    /**
     * Is Included
     */
    is_included?: boolean;
    /**
     * Id
     */
    id: string;
    /**
     * Resume Id
     */
    resume_id?: string | null;
    /**
     * Created At
     */
    created_at: Date;
};

/**
 * ResumeSummary
 */
export type ResumeSummary = {
    /**
     * Total Records
     */
    total_records: number;
};

/**
 * RoleRead
 */
export type RoleRead = {
    /**
     * Name
     *
     * Name of the role within the system.
     */
    name: 'admin' | 'manager' | 'user';
    /**
     * Id
     */
    id: number;
};

/**
 * TrainingProgramCreate
 */
export type TrainingProgramCreate = {
    /**
     * Program Name
     */
    program_name: string;
    /**
     * Start Date
     */
    start_date: Date;
    /**
     * End Date
     */
    end_date: Date;
    /**
     * Organizing Institution
     */
    organizing_institution?: string | null;
    /**
     * Completion Status
     */
    completion_status?: boolean;
    /**
     * Display Order
     */
    display_order?: number;
    /**
     * Resume Id
     */
    resume_id?: string | null;
};

/**
 * TrainingProgramRead
 */
export type TrainingProgramRead = {
    /**
     * Program Name
     */
    program_name: string;
    /**
     * Start Date
     */
    start_date: Date;
    /**
     * End Date
     */
    end_date: Date;
    /**
     * Organizing Institution
     */
    organizing_institution?: string | null;
    /**
     * Completion Status
     */
    completion_status?: boolean;
    /**
     * Display Order
     */
    display_order?: number;
    /**
     * Id
     */
    id: string;
    /**
     * Resume Id
     */
    resume_id?: string | null;
    /**
     * Created At
     */
    created_at: Date;
};

/**
 * UserCreate
 */
export type UserCreate = {
    /**
     * Username
     */
    username: string;
    /**
     * Name
     */
    name?: string | null;
    /**
     * Profile Photo Url
     */
    profile_photo_url?: string | null;
    /**
     * Is Active
     */
    is_active?: boolean;
    /**
     * Email
     */
    email: string;
    /**
     * Password
     */
    password?: string | null;
    /**
     * Google Id
     */
    google_id?: string | null;
    /**
     * Google Refresh Token
     */
    google_refresh_token?: string | null;
    /**
     * Google Access Token
     */
    google_access_token?: string | null;
    /**
     * Google Auth Active
     */
    google_auth_active?: boolean;
    /**
     * Role Name
     *
     * Optional role override when creating privileged users.
     */
    role_name?: 'admin' | 'manager' | 'user' | null;
};

/**
 * UserRead
 */
export type UserRead = {
    /**
     * Username
     */
    username: string;
    /**
     * Name
     */
    name?: string | null;
    /**
     * Profile Photo Url
     */
    profile_photo_url?: string | null;
    /**
     * Is Active
     */
    is_active?: boolean;
    /**
     * Id
     */
    id: string;
    /**
     * Email
     */
    email: string;
    role: RoleRead;
    /**
     * Google Id
     */
    google_id?: string | null;
    /**
     * Google Auth Active
     */
    google_auth_active: boolean;
    /**
     * Last Login
     */
    last_login?: Date | null;
    /**
     * Created At
     */
    created_at: Date;
    /**
     * Updated At
     */
    updated_at: Date;
    /**
     * Is Deleted
     */
    is_deleted: boolean;
};

/**
 * UserSessionRead
 */
export type UserSessionRead = {
    /**
     * Session Token
     */
    session_token: string;
    /**
     * Refresh Token
     */
    refresh_token?: string | null;
    /**
     * Expires At
     */
    expires_at: Date;
    /**
     * User Agent
     */
    user_agent?: string | null;
    /**
     * Ip Address
     */
    ip_address?: string | null;
    /**
     * Is Active
     */
    is_active?: boolean;
    /**
     * Id
     */
    id: string;
    /**
     * User Id
     */
    user_id?: string | null;
    /**
     * Created At
     */
    created_at: Date;
};

/**
 * UserUpdate
 */
export type UserUpdate = {
    /**
     * Email
     */
    email?: string | null;
    /**
     * Username
     */
    username?: string | null;
    /**
     * Name
     */
    name?: string | null;
    /**
     * Profile Photo Url
     */
    profile_photo_url?: string | null;
    /**
     * Is Active
     */
    is_active?: boolean | null;
    /**
     * Password
     */
    password?: string | null;
    /**
     * Google Id
     */
    google_id?: string | null;
    /**
     * Google Refresh Token
     */
    google_refresh_token?: string | null;
    /**
     * Google Access Token
     */
    google_access_token?: string | null;
    /**
     * Google Auth Active
     */
    google_auth_active?: boolean | null;
    /**
     * Role Name
     */
    role_name?: 'admin' | 'manager' | 'user' | null;
    /**
     * Is Deleted
     */
    is_deleted?: boolean | null;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
};

/**
 * WorkExperienceCreate
 */
export type WorkExperienceCreate = {
    /**
     * Start Date
     */
    start_date: Date;
    /**
     * End Date
     */
    end_date?: Date | null;
    /**
     * Organization
     */
    organization: string;
    /**
     * Department
     */
    department?: string | null;
    /**
     * Position
     */
    position?: string | null;
    /**
     * Responsibilities
     */
    responsibilities?: string | null;
    /**
     * Current Job
     */
    current_job?: boolean;
    /**
     * Display Order
     */
    display_order?: number;
    /**
     * Resume Id
     */
    resume_id?: string | null;
};

/**
 * WorkExperienceRead
 */
export type WorkExperienceRead = {
    /**
     * Start Date
     */
    start_date: Date;
    /**
     * End Date
     */
    end_date?: Date | null;
    /**
     * Organization
     */
    organization: string;
    /**
     * Department
     */
    department?: string | null;
    /**
     * Position
     */
    position?: string | null;
    /**
     * Responsibilities
     */
    responsibilities?: string | null;
    /**
     * Current Job
     */
    current_job?: boolean;
    /**
     * Display Order
     */
    display_order?: number;
    /**
     * Id
     */
    id: string;
    /**
     * Resume Id
     */
    resume_id?: string | null;
    /**
     * Created At
     */
    created_at: Date;
};

export type AuthGetStatusData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/auth/status';
};

export type AuthGetStatusResponses = {
    /**
     * Successful Response
     */
    200: AuthStatus;
};

export type AuthGetStatusResponse = AuthGetStatusResponses[keyof AuthGetStatusResponses];

export type AuthLoginData = {
    body: LoginRequest;
    path?: never;
    query?: never;
    url: '/api/v1/auth/login';
};

export type AuthLoginErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AuthLoginError = AuthLoginErrors[keyof AuthLoginErrors];

export type AuthLoginResponses = {
    /**
     * Successful Response
     */
    200: LoginResponse;
};

export type AuthLoginResponse = AuthLoginResponses[keyof AuthLoginResponses];

export type AuthRequestPasswordResetData = {
    body: PasswordResetRequest;
    path?: never;
    query?: never;
    url: '/api/v1/auth/password-reset/token';
};

export type AuthRequestPasswordResetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AuthRequestPasswordResetError = AuthRequestPasswordResetErrors[keyof AuthRequestPasswordResetErrors];

export type AuthRequestPasswordResetResponses = {
    /**
     * Successful Response
     */
    200: PasswordResetToken;
};

export type AuthRequestPasswordResetResponse = AuthRequestPasswordResetResponses[keyof AuthRequestPasswordResetResponses];

export type AuthResetPasswordData = {
    body: PasswordResetConfirm;
    path?: never;
    query?: never;
    url: '/api/v1/auth/password-reset';
};

export type AuthResetPasswordErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AuthResetPasswordError = AuthResetPasswordErrors[keyof AuthResetPasswordErrors];

export type AuthResetPasswordResponses = {
    /**
     * Successful Response
     */
    200: UserRead;
};

export type AuthResetPasswordResponse = AuthResetPasswordResponses[keyof AuthResetPasswordResponses];

export type AuthListUsersData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Limit
         */
        limit?: number;
        /**
         * Offset
         */
        offset?: number;
    };
    url: '/api/v1/auth/users';
};

export type AuthListUsersErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AuthListUsersError = AuthListUsersErrors[keyof AuthListUsersErrors];

export type AuthListUsersResponses = {
    /**
     * Response Auth-List Users
     *
     * Successful Response
     */
    200: Array<UserRead>;
};

export type AuthListUsersResponse = AuthListUsersResponses[keyof AuthListUsersResponses];

export type AuthCreateUserData = {
    body: UserCreate;
    path?: never;
    query?: never;
    url: '/api/v1/auth/users';
};

export type AuthCreateUserErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AuthCreateUserError = AuthCreateUserErrors[keyof AuthCreateUserErrors];

export type AuthCreateUserResponses = {
    /**
     * Successful Response
     */
    201: UserRead;
};

export type AuthCreateUserResponse = AuthCreateUserResponses[keyof AuthCreateUserResponses];

export type AuthGetUserData = {
    body?: never;
    path: {
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/api/v1/auth/users/{user_id}';
};

export type AuthGetUserErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AuthGetUserError = AuthGetUserErrors[keyof AuthGetUserErrors];

export type AuthGetUserResponses = {
    /**
     * Successful Response
     */
    200: UserRead;
};

export type AuthGetUserResponse = AuthGetUserResponses[keyof AuthGetUserResponses];

export type AuthUpdateUserData = {
    body: UserUpdate;
    path: {
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/api/v1/auth/users/{user_id}';
};

export type AuthUpdateUserErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AuthUpdateUserError = AuthUpdateUserErrors[keyof AuthUpdateUserErrors];

export type AuthUpdateUserResponses = {
    /**
     * Successful Response
     */
    200: UserRead;
};

export type AuthUpdateUserResponse = AuthUpdateUserResponses[keyof AuthUpdateUserResponses];

export type AuthActivateGoogleLoginData = {
    body: GoogleAuthActivate;
    path: {
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/api/v1/auth/{user_id}/google/activate';
};

export type AuthActivateGoogleLoginErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AuthActivateGoogleLoginError = AuthActivateGoogleLoginErrors[keyof AuthActivateGoogleLoginErrors];

export type AuthActivateGoogleLoginResponses = {
    /**
     * Successful Response
     */
    200: UserRead;
};

export type AuthActivateGoogleLoginResponse = AuthActivateGoogleLoginResponses[keyof AuthActivateGoogleLoginResponses];

export type AuthUpdateGoogleTokensData = {
    body: GoogleTokenUpdate;
    path: {
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/api/v1/auth/{user_id}/google/tokens';
};

export type AuthUpdateGoogleTokensErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AuthUpdateGoogleTokensError = AuthUpdateGoogleTokensErrors[keyof AuthUpdateGoogleTokensErrors];

export type AuthUpdateGoogleTokensResponses = {
    /**
     * Successful Response
     */
    200: UserRead;
};

export type AuthUpdateGoogleTokensResponse = AuthUpdateGoogleTokensResponses[keyof AuthUpdateGoogleTokensResponses];

export type AuthDeactivateGoogleLoginData = {
    body?: never;
    path: {
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/api/v1/auth/{user_id}/google';
};

export type AuthDeactivateGoogleLoginErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AuthDeactivateGoogleLoginError = AuthDeactivateGoogleLoginErrors[keyof AuthDeactivateGoogleLoginErrors];

export type AuthDeactivateGoogleLoginResponses = {
    /**
     * Successful Response
     */
    200: UserRead;
};

export type AuthDeactivateGoogleLoginResponse = AuthDeactivateGoogleLoginResponses[keyof AuthDeactivateGoogleLoginResponses];

export type ResumesListResumesData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Limit
         */
        limit?: number;
        /**
         * Offset
         */
        offset?: number;
        /**
         * User Id
         */
        user_id?: string | null;
    };
    url: '/api/v1/resumes/';
};

export type ResumesListResumesErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ResumesListResumesError = ResumesListResumesErrors[keyof ResumesListResumesErrors];

export type ResumesListResumesResponses = {
    /**
     * Response Resumes-List Resumes
     *
     * Successful Response
     */
    200: Array<ResumeRead>;
};

export type ResumesListResumesResponse = ResumesListResumesResponses[keyof ResumesListResumesResponses];

export type ResumesCreateResumeData = {
    body: ResumeCreate;
    path?: never;
    query?: never;
    url: '/api/v1/resumes/';
};

export type ResumesCreateResumeErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ResumesCreateResumeError = ResumesCreateResumeErrors[keyof ResumesCreateResumeErrors];

export type ResumesCreateResumeResponses = {
    /**
     * Successful Response
     */
    201: ResumeRead;
};

export type ResumesCreateResumeResponse = ResumesCreateResumeResponses[keyof ResumesCreateResumeResponses];

export type ResumesSummaryData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/resumes/summary';
};

export type ResumesSummaryResponses = {
    /**
     * Successful Response
     */
    200: ResumeSummary;
};

export type ResumesSummaryResponse = ResumesSummaryResponses[keyof ResumesSummaryResponses];

export type ResumesDeleteResumeData = {
    body?: never;
    path: {
        /**
         * Resume Id
         */
        resume_id: string;
    };
    query?: never;
    url: '/api/v1/resumes/{resume_id}';
};

export type ResumesDeleteResumeErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ResumesDeleteResumeError = ResumesDeleteResumeErrors[keyof ResumesDeleteResumeErrors];

export type ResumesDeleteResumeResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type ResumesDeleteResumeResponse = ResumesDeleteResumeResponses[keyof ResumesDeleteResumeResponses];

export type ResumesGetResumeData = {
    body?: never;
    path: {
        /**
         * Resume Id
         */
        resume_id: string;
    };
    query?: never;
    url: '/api/v1/resumes/{resume_id}';
};

export type ResumesGetResumeErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ResumesGetResumeError = ResumesGetResumeErrors[keyof ResumesGetResumeErrors];

export type ResumesGetResumeResponses = {
    /**
     * Successful Response
     */
    200: ResumeRead;
};

export type ResumesGetResumeResponse = ResumesGetResumeResponses[keyof ResumesGetResumeResponses];

export type ResumesUpdateResumeData = {
    body: ResumeCreate;
    path: {
        /**
         * Resume Id
         */
        resume_id: string;
    };
    query?: never;
    url: '/api/v1/resumes/{resume_id}';
};

export type ResumesUpdateResumeErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ResumesUpdateResumeError = ResumesUpdateResumeErrors[keyof ResumesUpdateResumeErrors];

export type ResumesUpdateResumeResponses = {
    /**
     * Successful Response
     */
    200: ResumeRead;
};

export type ResumesUpdateResumeResponse = ResumesUpdateResumeResponses[keyof ResumesUpdateResumeResponses];

export type ResumesGetFullResumeData = {
    body?: never;
    path: {
        /**
         * Resume Id
         */
        resume_id: string;
    };
    query?: never;
    url: '/api/v1/resumes/{resume_id}/full';
};

export type ResumesGetFullResumeErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ResumesGetFullResumeError = ResumesGetFullResumeErrors[keyof ResumesGetFullResumeErrors];

export type ResumesGetFullResumeResponses = {
    /**
     * Successful Response
     */
    200: ResumeDetail;
};

export type ResumesGetFullResumeResponse = ResumesGetFullResumeResponses[keyof ResumesGetFullResumeResponses];

export type ResumesListProfilesData = {
    body?: never;
    path: {
        /**
         * Resume Id
         */
        resume_id: string;
    };
    query?: never;
    url: '/api/v1/resumes/{resume_id}/profiles';
};

export type ResumesListProfilesErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ResumesListProfilesError = ResumesListProfilesErrors[keyof ResumesListProfilesErrors];

export type ResumesListProfilesResponses = {
    /**
     * Response Resumes-List Profiles
     *
     * Successful Response
     */
    200: Array<PersonalProfileRead>;
};

export type ResumesListProfilesResponse = ResumesListProfilesResponses[keyof ResumesListProfilesResponses];

export type ResumesCreateProfileData = {
    body: PersonalProfileCreate;
    path: {
        /**
         * Resume Id
         */
        resume_id: string;
    };
    query?: never;
    url: '/api/v1/resumes/{resume_id}/profiles';
};

export type ResumesCreateProfileErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ResumesCreateProfileError = ResumesCreateProfileErrors[keyof ResumesCreateProfileErrors];

export type ResumesCreateProfileResponses = {
    /**
     * Successful Response
     */
    201: PersonalProfileRead;
};

export type ResumesCreateProfileResponse = ResumesCreateProfileResponses[keyof ResumesCreateProfileResponses];

export type ResumesDeleteProfileData = {
    body?: never;
    path: {
        /**
         * Profile Id
         */
        profile_id: string;
    };
    query?: never;
    url: '/api/v1/resumes/profiles/{profile_id}';
};

export type ResumesDeleteProfileErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ResumesDeleteProfileError = ResumesDeleteProfileErrors[keyof ResumesDeleteProfileErrors];

export type ResumesDeleteProfileResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type ResumesDeleteProfileResponse = ResumesDeleteProfileResponses[keyof ResumesDeleteProfileResponses];

export type ResumesListEducationData = {
    body?: never;
    path: {
        /**
         * Resume Id
         */
        resume_id: string;
    };
    query?: never;
    url: '/api/v1/resumes/{resume_id}/education';
};

export type ResumesListEducationErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ResumesListEducationError = ResumesListEducationErrors[keyof ResumesListEducationErrors];

export type ResumesListEducationResponses = {
    /**
     * Response Resumes-List Education
     *
     * Successful Response
     */
    200: Array<EducationHistoryRead>;
};

export type ResumesListEducationResponse = ResumesListEducationResponses[keyof ResumesListEducationResponses];

export type ResumesCreateEducationData = {
    body: EducationHistoryCreate;
    path: {
        /**
         * Resume Id
         */
        resume_id: string;
    };
    query?: never;
    url: '/api/v1/resumes/{resume_id}/education';
};

export type ResumesCreateEducationErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ResumesCreateEducationError = ResumesCreateEducationErrors[keyof ResumesCreateEducationErrors];

export type ResumesCreateEducationResponses = {
    /**
     * Successful Response
     */
    201: EducationHistoryRead;
};

export type ResumesCreateEducationResponse = ResumesCreateEducationResponses[keyof ResumesCreateEducationResponses];

export type ResumesDeleteEducationData = {
    body?: never;
    path: {
        /**
         * Entry Id
         */
        entry_id: string;
    };
    query?: never;
    url: '/api/v1/resumes/education/{entry_id}';
};

export type ResumesDeleteEducationErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ResumesDeleteEducationError = ResumesDeleteEducationErrors[keyof ResumesDeleteEducationErrors];

export type ResumesDeleteEducationResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type ResumesDeleteEducationResponse = ResumesDeleteEducationResponses[keyof ResumesDeleteEducationResponses];

export type ResumesListFamilyData = {
    body?: never;
    path: {
        /**
         * Resume Id
         */
        resume_id: string;
    };
    query?: never;
    url: '/api/v1/resumes/{resume_id}/family';
};

export type ResumesListFamilyErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ResumesListFamilyError = ResumesListFamilyErrors[keyof ResumesListFamilyErrors];

export type ResumesListFamilyResponses = {
    /**
     * Response Resumes-List Family
     *
     * Successful Response
     */
    200: Array<FamilyMemberRead>;
};

export type ResumesListFamilyResponse = ResumesListFamilyResponses[keyof ResumesListFamilyResponses];

export type ResumesCreateFamilyMemberData = {
    body: FamilyMemberCreate;
    path: {
        /**
         * Resume Id
         */
        resume_id: string;
    };
    query?: never;
    url: '/api/v1/resumes/{resume_id}/family';
};

export type ResumesCreateFamilyMemberErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ResumesCreateFamilyMemberError = ResumesCreateFamilyMemberErrors[keyof ResumesCreateFamilyMemberErrors];

export type ResumesCreateFamilyMemberResponses = {
    /**
     * Successful Response
     */
    201: FamilyMemberRead;
};

export type ResumesCreateFamilyMemberResponse = ResumesCreateFamilyMemberResponses[keyof ResumesCreateFamilyMemberResponses];

export type ResumesDeleteFamilyMemberData = {
    body?: never;
    path: {
        /**
         * Member Id
         */
        member_id: string;
    };
    query?: never;
    url: '/api/v1/resumes/family/{member_id}';
};

export type ResumesDeleteFamilyMemberErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ResumesDeleteFamilyMemberError = ResumesDeleteFamilyMemberErrors[keyof ResumesDeleteFamilyMemberErrors];

export type ResumesDeleteFamilyMemberResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type ResumesDeleteFamilyMemberResponse = ResumesDeleteFamilyMemberResponses[keyof ResumesDeleteFamilyMemberResponses];

export type ResumesListWorkData = {
    body?: never;
    path: {
        /**
         * Resume Id
         */
        resume_id: string;
    };
    query?: never;
    url: '/api/v1/resumes/{resume_id}/work';
};

export type ResumesListWorkErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ResumesListWorkError = ResumesListWorkErrors[keyof ResumesListWorkErrors];

export type ResumesListWorkResponses = {
    /**
     * Response Resumes-List Work
     *
     * Successful Response
     */
    200: Array<WorkExperienceRead>;
};

export type ResumesListWorkResponse = ResumesListWorkResponses[keyof ResumesListWorkResponses];

export type ResumesCreateWorkExperienceData = {
    body: WorkExperienceCreate;
    path: {
        /**
         * Resume Id
         */
        resume_id: string;
    };
    query?: never;
    url: '/api/v1/resumes/{resume_id}/work';
};

export type ResumesCreateWorkExperienceErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ResumesCreateWorkExperienceError = ResumesCreateWorkExperienceErrors[keyof ResumesCreateWorkExperienceErrors];

export type ResumesCreateWorkExperienceResponses = {
    /**
     * Successful Response
     */
    201: WorkExperienceRead;
};

export type ResumesCreateWorkExperienceResponse = ResumesCreateWorkExperienceResponses[keyof ResumesCreateWorkExperienceResponses];

export type ResumesDeleteWorkExperienceData = {
    body?: never;
    path: {
        /**
         * Experience Id
         */
        experience_id: string;
    };
    query?: never;
    url: '/api/v1/resumes/work/{experience_id}';
};

export type ResumesDeleteWorkExperienceErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ResumesDeleteWorkExperienceError = ResumesDeleteWorkExperienceErrors[keyof ResumesDeleteWorkExperienceErrors];

export type ResumesDeleteWorkExperienceResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type ResumesDeleteWorkExperienceResponse = ResumesDeleteWorkExperienceResponses[keyof ResumesDeleteWorkExperienceResponses];

export type ResumesListActivitiesData = {
    body?: never;
    path: {
        /**
         * Resume Id
         */
        resume_id: string;
    };
    query?: never;
    url: '/api/v1/resumes/{resume_id}/activities';
};

export type ResumesListActivitiesErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ResumesListActivitiesError = ResumesListActivitiesErrors[keyof ResumesListActivitiesErrors];

export type ResumesListActivitiesResponses = {
    /**
     * Response Resumes-List Activities
     *
     * Successful Response
     */
    200: Array<OrganizationalActivityRead>;
};

export type ResumesListActivitiesResponse = ResumesListActivitiesResponses[keyof ResumesListActivitiesResponses];

export type ResumesCreateActivityData = {
    body: OrganizationalActivityCreate;
    path: {
        /**
         * Resume Id
         */
        resume_id: string;
    };
    query?: never;
    url: '/api/v1/resumes/{resume_id}/activities';
};

export type ResumesCreateActivityErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ResumesCreateActivityError = ResumesCreateActivityErrors[keyof ResumesCreateActivityErrors];

export type ResumesCreateActivityResponses = {
    /**
     * Successful Response
     */
    201: OrganizationalActivityRead;
};

export type ResumesCreateActivityResponse = ResumesCreateActivityResponses[keyof ResumesCreateActivityResponses];

export type ResumesDeleteActivityData = {
    body?: never;
    path: {
        /**
         * Activity Id
         */
        activity_id: string;
    };
    query?: never;
    url: '/api/v1/resumes/activities/{activity_id}';
};

export type ResumesDeleteActivityErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ResumesDeleteActivityError = ResumesDeleteActivityErrors[keyof ResumesDeleteActivityErrors];

export type ResumesDeleteActivityResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type ResumesDeleteActivityResponse = ResumesDeleteActivityResponses[keyof ResumesDeleteActivityResponses];

export type ResumesListTrainingData = {
    body?: never;
    path: {
        /**
         * Resume Id
         */
        resume_id: string;
    };
    query?: never;
    url: '/api/v1/resumes/{resume_id}/training';
};

export type ResumesListTrainingErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ResumesListTrainingError = ResumesListTrainingErrors[keyof ResumesListTrainingErrors];

export type ResumesListTrainingResponses = {
    /**
     * Response Resumes-List Training
     *
     * Successful Response
     */
    200: Array<TrainingProgramRead>;
};

export type ResumesListTrainingResponse = ResumesListTrainingResponses[keyof ResumesListTrainingResponses];

export type ResumesCreateTrainingData = {
    body: TrainingProgramCreate;
    path: {
        /**
         * Resume Id
         */
        resume_id: string;
    };
    query?: never;
    url: '/api/v1/resumes/{resume_id}/training';
};

export type ResumesCreateTrainingErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ResumesCreateTrainingError = ResumesCreateTrainingErrors[keyof ResumesCreateTrainingErrors];

export type ResumesCreateTrainingResponses = {
    /**
     * Successful Response
     */
    201: TrainingProgramRead;
};

export type ResumesCreateTrainingResponse = ResumesCreateTrainingResponses[keyof ResumesCreateTrainingResponses];

export type ResumesDeleteTrainingData = {
    body?: never;
    path: {
        /**
         * Program Id
         */
        program_id: string;
    };
    query?: never;
    url: '/api/v1/resumes/training/{program_id}';
};

export type ResumesDeleteTrainingErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ResumesDeleteTrainingError = ResumesDeleteTrainingErrors[keyof ResumesDeleteTrainingErrors];

export type ResumesDeleteTrainingResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type ResumesDeleteTrainingResponse = ResumesDeleteTrainingResponses[keyof ResumesDeleteTrainingResponses];

export type ResumesListCertificationsData = {
    body?: never;
    path: {
        /**
         * Resume Id
         */
        resume_id: string;
    };
    query?: never;
    url: '/api/v1/resumes/{resume_id}/certifications';
};

export type ResumesListCertificationsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ResumesListCertificationsError = ResumesListCertificationsErrors[keyof ResumesListCertificationsErrors];

export type ResumesListCertificationsResponses = {
    /**
     * Response Resumes-List Certifications
     *
     * Successful Response
     */
    200: Array<CertificationRead>;
};

export type ResumesListCertificationsResponse = ResumesListCertificationsResponses[keyof ResumesListCertificationsResponses];

export type ResumesCreateCertificationData = {
    body: CertificationCreate;
    path: {
        /**
         * Resume Id
         */
        resume_id: string;
    };
    query?: never;
    url: '/api/v1/resumes/{resume_id}/certifications';
};

export type ResumesCreateCertificationErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ResumesCreateCertificationError = ResumesCreateCertificationErrors[keyof ResumesCreateCertificationErrors];

export type ResumesCreateCertificationResponses = {
    /**
     * Successful Response
     */
    201: CertificationRead;
};

export type ResumesCreateCertificationResponse = ResumesCreateCertificationResponses[keyof ResumesCreateCertificationResponses];

export type ResumesDeleteCertificationData = {
    body?: never;
    path: {
        /**
         * Certification Id
         */
        certification_id: string;
    };
    query?: never;
    url: '/api/v1/resumes/certifications/{certification_id}';
};

export type ResumesDeleteCertificationErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ResumesDeleteCertificationError = ResumesDeleteCertificationErrors[keyof ResumesDeleteCertificationErrors];

export type ResumesDeleteCertificationResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type ResumesDeleteCertificationResponse = ResumesDeleteCertificationResponses[keyof ResumesDeleteCertificationResponses];

export type ResumesListAwardsData = {
    body?: never;
    path: {
        /**
         * Resume Id
         */
        resume_id: string;
    };
    query?: never;
    url: '/api/v1/resumes/{resume_id}/awards';
};

export type ResumesListAwardsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ResumesListAwardsError = ResumesListAwardsErrors[keyof ResumesListAwardsErrors];

export type ResumesListAwardsResponses = {
    /**
     * Response Resumes-List Awards
     *
     * Successful Response
     */
    200: Array<AwardRead>;
};

export type ResumesListAwardsResponse = ResumesListAwardsResponses[keyof ResumesListAwardsResponses];

export type ResumesCreateAwardData = {
    body: AwardCreate;
    path: {
        /**
         * Resume Id
         */
        resume_id: string;
    };
    query?: never;
    url: '/api/v1/resumes/{resume_id}/awards';
};

export type ResumesCreateAwardErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ResumesCreateAwardError = ResumesCreateAwardErrors[keyof ResumesCreateAwardErrors];

export type ResumesCreateAwardResponses = {
    /**
     * Successful Response
     */
    201: AwardRead;
};

export type ResumesCreateAwardResponse = ResumesCreateAwardResponses[keyof ResumesCreateAwardResponses];

export type ResumesDeleteAwardData = {
    body?: never;
    path: {
        /**
         * Award Id
         */
        award_id: string;
    };
    query?: never;
    url: '/api/v1/resumes/awards/{award_id}';
};

export type ResumesDeleteAwardErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ResumesDeleteAwardError = ResumesDeleteAwardErrors[keyof ResumesDeleteAwardErrors];

export type ResumesDeleteAwardResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type ResumesDeleteAwardResponse = ResumesDeleteAwardResponses[keyof ResumesDeleteAwardResponses];

export type ResumesListDisciplineData = {
    body?: never;
    path: {
        /**
         * Resume Id
         */
        resume_id: string;
    };
    query?: never;
    url: '/api/v1/resumes/{resume_id}/discipline';
};

export type ResumesListDisciplineErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ResumesListDisciplineError = ResumesListDisciplineErrors[keyof ResumesListDisciplineErrors];

export type ResumesListDisciplineResponses = {
    /**
     * Response Resumes-List Discipline
     *
     * Successful Response
     */
    200: Array<DisciplineRecordRead>;
};

export type ResumesListDisciplineResponse = ResumesListDisciplineResponses[keyof ResumesListDisciplineResponses];

export type ResumesCreateDisciplineRecordData = {
    body: DisciplineRecordCreate;
    path: {
        /**
         * Resume Id
         */
        resume_id: string;
    };
    query?: never;
    url: '/api/v1/resumes/{resume_id}/discipline';
};

export type ResumesCreateDisciplineRecordErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ResumesCreateDisciplineRecordError = ResumesCreateDisciplineRecordErrors[keyof ResumesCreateDisciplineRecordErrors];

export type ResumesCreateDisciplineRecordResponses = {
    /**
     * Successful Response
     */
    201: DisciplineRecordRead;
};

export type ResumesCreateDisciplineRecordResponse = ResumesCreateDisciplineRecordResponses[keyof ResumesCreateDisciplineRecordResponses];

export type ResumesDeleteDisciplineRecordData = {
    body?: never;
    path: {
        /**
         * Record Id
         */
        record_id: string;
    };
    query?: never;
    url: '/api/v1/resumes/discipline/{record_id}';
};

export type ResumesDeleteDisciplineRecordErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ResumesDeleteDisciplineRecordError = ResumesDeleteDisciplineRecordErrors[keyof ResumesDeleteDisciplineRecordErrors];

export type ResumesDeleteDisciplineRecordResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type ResumesDeleteDisciplineRecordResponse = ResumesDeleteDisciplineRecordResponses[keyof ResumesDeleteDisciplineRecordResponses];

export type ResumesListRemarksData = {
    body?: never;
    path: {
        /**
         * Resume Id
         */
        resume_id: string;
    };
    query?: never;
    url: '/api/v1/resumes/{resume_id}/remarks';
};

export type ResumesListRemarksErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ResumesListRemarksError = ResumesListRemarksErrors[keyof ResumesListRemarksErrors];

export type ResumesListRemarksResponses = {
    /**
     * Response Resumes-List Remarks
     *
     * Successful Response
     */
    200: Array<AdditionalRemarkRead>;
};

export type ResumesListRemarksResponse = ResumesListRemarksResponses[keyof ResumesListRemarksResponses];

export type ResumesCreateRemarkData = {
    body: AdditionalRemarkCreate;
    path: {
        /**
         * Resume Id
         */
        resume_id: string;
    };
    query?: never;
    url: '/api/v1/resumes/{resume_id}/remarks';
};

export type ResumesCreateRemarkErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ResumesCreateRemarkError = ResumesCreateRemarkErrors[keyof ResumesCreateRemarkErrors];

export type ResumesCreateRemarkResponses = {
    /**
     * Successful Response
     */
    201: AdditionalRemarkRead;
};

export type ResumesCreateRemarkResponse = ResumesCreateRemarkResponses[keyof ResumesCreateRemarkResponses];

export type ResumesDeleteRemarkData = {
    body?: never;
    path: {
        /**
         * Remark Id
         */
        remark_id: string;
    };
    query?: never;
    url: '/api/v1/resumes/remarks/{remark_id}';
};

export type ResumesDeleteRemarkErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ResumesDeleteRemarkError = ResumesDeleteRemarkErrors[keyof ResumesDeleteRemarkErrors];

export type ResumesDeleteRemarkResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type ResumesDeleteRemarkResponse = ResumesDeleteRemarkResponses[keyof ResumesDeleteRemarkResponses];

export type ResumesListSectionsData = {
    body?: never;
    path: {
        /**
         * Resume Id
         */
        resume_id: string;
    };
    query?: never;
    url: '/api/v1/resumes/{resume_id}/sections';
};

export type ResumesListSectionsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ResumesListSectionsError = ResumesListSectionsErrors[keyof ResumesListSectionsErrors];

export type ResumesListSectionsResponses = {
    /**
     * Response Resumes-List Sections
     *
     * Successful Response
     */
    200: Array<ResumeSectionRead>;
};

export type ResumesListSectionsResponse = ResumesListSectionsResponses[keyof ResumesListSectionsResponses];

export type ResumesCreateSectionData = {
    body: ResumeSectionCreate;
    path: {
        /**
         * Resume Id
         */
        resume_id: string;
    };
    query?: never;
    url: '/api/v1/resumes/{resume_id}/sections';
};

export type ResumesCreateSectionErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ResumesCreateSectionError = ResumesCreateSectionErrors[keyof ResumesCreateSectionErrors];

export type ResumesCreateSectionResponses = {
    /**
     * Successful Response
     */
    201: ResumeSectionRead;
};

export type ResumesCreateSectionResponse = ResumesCreateSectionResponses[keyof ResumesCreateSectionResponses];

export type ResumesDeleteSectionData = {
    body?: never;
    path: {
        /**
         * Section Id
         */
        section_id: string;
    };
    query?: never;
    url: '/api/v1/resumes/sections/{section_id}';
};

export type ResumesDeleteSectionErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ResumesDeleteSectionError = ResumesDeleteSectionErrors[keyof ResumesDeleteSectionErrors];

export type ResumesDeleteSectionResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type ResumesDeleteSectionResponse = ResumesDeleteSectionResponses[keyof ResumesDeleteSectionResponses];

export type ResumesUpdateSectionData = {
    body: ResumeSectionCreate;
    path: {
        /**
         * Section Id
         */
        section_id: string;
    };
    query?: never;
    url: '/api/v1/resumes/sections/{section_id}';
};

export type ResumesUpdateSectionErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ResumesUpdateSectionError = ResumesUpdateSectionErrors[keyof ResumesUpdateSectionErrors];

export type ResumesUpdateSectionResponses = {
    /**
     * Successful Response
     */
    200: ResumeSectionRead;
};

export type ResumesUpdateSectionResponse = ResumesUpdateSectionResponses[keyof ResumesUpdateSectionResponses];

export type ResumesListUserSessionsData = {
    body?: never;
    path: {
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/api/v1/resumes/users/{user_id}/sessions';
};

export type ResumesListUserSessionsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ResumesListUserSessionsError = ResumesListUserSessionsErrors[keyof ResumesListUserSessionsErrors];

export type ResumesListUserSessionsResponses = {
    /**
     * Response Resumes-List User Sessions
     *
     * Successful Response
     */
    200: Array<UserSessionRead>;
};

export type ResumesListUserSessionsResponse = ResumesListUserSessionsResponses[keyof ResumesListUserSessionsResponses];

export type ResumesListEmailTokensData = {
    body?: never;
    path: {
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/api/v1/resumes/users/{user_id}/email-tokens';
};

export type ResumesListEmailTokensErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ResumesListEmailTokensError = ResumesListEmailTokensErrors[keyof ResumesListEmailTokensErrors];

export type ResumesListEmailTokensResponses = {
    /**
     * Response Resumes-List Email Tokens
     *
     * Successful Response
     */
    200: Array<EmailVerificationTokenRead>;
};

export type ResumesListEmailTokensResponse = ResumesListEmailTokensResponses[keyof ResumesListEmailTokensResponses];
