// This file is auto-generated by @hey-api/openapi-ts

import { z } from 'zod';

/**
 * AdditionalRemarkCreate
 */
export const zAdditionalRemarkCreate = z.object({
    registration_date: z.iso.date(),
    content: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    display_order: z.optional(z.int()).default(0),
    resume_id: z.optional(z.union([
        z.uuid(),
        z.null()
    ]))
});

/**
 * AdditionalRemarkRead
 */
export const zAdditionalRemarkRead = z.object({
    registration_date: z.iso.date(),
    content: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    display_order: z.optional(z.int()).default(0),
    id: z.uuid(),
    resume_id: z.optional(z.union([
        z.uuid(),
        z.null()
    ])),
    created_at: z.iso.datetime()
});

/**
 * AuthStatus
 */
export const zAuthStatus = z.object({
    healthy: z.boolean()
});

/**
 * AwardCreate
 */
export const zAwardCreate = z.object({
    award_date: z.iso.date(),
    category: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    details: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    awarding_institution: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    display_order: z.optional(z.int()).default(0),
    resume_id: z.optional(z.union([
        z.uuid(),
        z.null()
    ]))
});

/**
 * AwardRead
 */
export const zAwardRead = z.object({
    award_date: z.iso.date(),
    category: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    details: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    awarding_institution: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    display_order: z.optional(z.int()).default(0),
    id: z.uuid(),
    resume_id: z.optional(z.union([
        z.uuid(),
        z.null()
    ])),
    created_at: z.iso.datetime()
});

/**
 * CertificationCreate
 */
export const zCertificationCreate = z.object({
    acquisition_date: z.iso.date(),
    certification_name: z.string(),
    remarks: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    display_order: z.optional(z.int()).default(0),
    resume_id: z.optional(z.union([
        z.uuid(),
        z.null()
    ]))
});

/**
 * CertificationRead
 */
export const zCertificationRead = z.object({
    acquisition_date: z.iso.date(),
    certification_name: z.string(),
    remarks: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    display_order: z.optional(z.int()).default(0),
    id: z.uuid(),
    resume_id: z.optional(z.union([
        z.uuid(),
        z.null()
    ])),
    created_at: z.iso.datetime()
});

/**
 * DisciplineRecordCreate
 */
export const zDisciplineRecordCreate = z.object({
    record_date: z.iso.date(),
    type: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    reason: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    display_order: z.optional(z.int()).default(0),
    resume_id: z.optional(z.union([
        z.uuid(),
        z.null()
    ]))
});

/**
 * DisciplineRecordRead
 */
export const zDisciplineRecordRead = z.object({
    record_date: z.iso.date(),
    type: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    reason: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    display_order: z.optional(z.int()).default(0),
    id: z.uuid(),
    resume_id: z.optional(z.union([
        z.uuid(),
        z.null()
    ])),
    created_at: z.iso.datetime()
});

/**
 * EducationHistoryCreate
 */
export const zEducationHistoryCreate = z.object({
    start_date: z.iso.date(),
    end_date: z.iso.date(),
    institution: z.string(),
    major: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    graduation_type: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    degree: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    display_order: z.optional(z.int()).default(0),
    resume_id: z.optional(z.union([
        z.uuid(),
        z.null()
    ]))
});

/**
 * EducationHistoryRead
 */
export const zEducationHistoryRead = z.object({
    start_date: z.iso.date(),
    end_date: z.iso.date(),
    institution: z.string(),
    major: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    graduation_type: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    degree: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    display_order: z.optional(z.int()).default(0),
    id: z.uuid(),
    resume_id: z.optional(z.union([
        z.uuid(),
        z.null()
    ])),
    created_at: z.iso.datetime()
});

/**
 * EmailVerificationTokenRead
 */
export const zEmailVerificationTokenRead = z.object({
    token: z.string(),
    expires_at: z.iso.datetime(),
    used_at: z.optional(z.union([
        z.iso.datetime(),
        z.null()
    ])),
    id: z.uuid(),
    user_id: z.optional(z.union([
        z.uuid(),
        z.null()
    ])),
    created_at: z.iso.datetime()
});

/**
 * FamilyMemberCreate
 */
export const zFamilyMemberCreate = z.object({
    relationship: z.string(),
    name: z.string(),
    birth_date: z.optional(z.union([
        z.iso.date(),
        z.null()
    ])),
    blessed: z.optional(z.boolean()).default(false),
    remarks: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    display_order: z.optional(z.int()).default(0),
    resume_id: z.optional(z.union([
        z.uuid(),
        z.null()
    ]))
});

/**
 * FamilyMemberRead
 */
export const zFamilyMemberRead = z.object({
    relationship: z.string(),
    name: z.string(),
    birth_date: z.optional(z.union([
        z.iso.date(),
        z.null()
    ])),
    blessed: z.optional(z.boolean()).default(false),
    remarks: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    display_order: z.optional(z.int()).default(0),
    id: z.uuid(),
    resume_id: z.optional(z.union([
        z.uuid(),
        z.null()
    ])),
    created_at: z.iso.datetime()
});

/**
 * GoogleAuthActivate
 */
export const zGoogleAuthActivate = z.object({
    google_id: z.string().min(5).max(255),
    google_refresh_token: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    google_access_token: z.optional(z.union([
        z.string(),
        z.null()
    ]))
});

/**
 * GoogleTokenUpdate
 */
export const zGoogleTokenUpdate = z.object({
    google_refresh_token: z.string().min(10),
    google_access_token: z.string().min(10)
});

/**
 * LoginRequest
 */
export const zLoginRequest = z.object({
    identifier: z.string().min(1),
    password: z.string().min(8)
});

/**
 * OrganizationalActivityCreate
 */
export const zOrganizationalActivityCreate = z.object({
    start_date: z.iso.date(),
    end_date: z.optional(z.union([
        z.iso.date(),
        z.null()
    ])),
    organization_name: z.string(),
    position: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    main_role: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    display_order: z.optional(z.int()).default(0),
    resume_id: z.optional(z.union([
        z.uuid(),
        z.null()
    ]))
});

/**
 * OrganizationalActivityRead
 */
export const zOrganizationalActivityRead = z.object({
    start_date: z.iso.date(),
    end_date: z.optional(z.union([
        z.iso.date(),
        z.null()
    ])),
    organization_name: z.string(),
    position: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    main_role: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    display_order: z.optional(z.int()).default(0),
    id: z.uuid(),
    resume_id: z.optional(z.union([
        z.uuid(),
        z.null()
    ])),
    created_at: z.iso.datetime()
});

/**
 * PasswordResetConfirm
 */
export const zPasswordResetConfirm = z.object({
    token: z.string(),
    new_password: z.string().min(8)
});

/**
 * PasswordResetRequest
 */
export const zPasswordResetRequest = z.object({
    identifier: z.string().min(1)
});

/**
 * PasswordResetToken
 */
export const zPasswordResetToken = z.object({
    token: z.string()
});

/**
 * PersonalProfileCreate
 */
export const zPersonalProfileCreate = z.object({
    korean_name: z.string(),
    english_name: z.string(),
    birth_date: z.iso.date(),
    chinese_name: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    resident_number: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    blessing_date: z.optional(z.union([
        z.iso.date(),
        z.null()
    ])),
    appointment_date: z.optional(z.union([
        z.iso.date(),
        z.null()
    ])),
    nationality: z.optional(z.union([
        z.string(),
        z.null()
    ])).default('대한민국'),
    organization: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    department: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    position: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    mobile_phone: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    extension: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    email: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    address: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    remarks: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    profile_update_date: z.optional(z.union([
        z.iso.date(),
        z.null()
    ])),
    resume_id: z.optional(z.union([
        z.uuid(),
        z.null()
    ]))
});

/**
 * PersonalProfileRead
 */
export const zPersonalProfileRead = z.object({
    korean_name: z.string(),
    english_name: z.string(),
    birth_date: z.iso.date(),
    chinese_name: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    resident_number: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    blessing_date: z.optional(z.union([
        z.iso.date(),
        z.null()
    ])),
    appointment_date: z.optional(z.union([
        z.iso.date(),
        z.null()
    ])),
    nationality: z.optional(z.union([
        z.string(),
        z.null()
    ])).default('대한민국'),
    organization: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    department: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    position: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    mobile_phone: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    extension: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    email: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    address: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    remarks: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    profile_update_date: z.optional(z.union([
        z.iso.date(),
        z.null()
    ])),
    id: z.uuid(),
    resume_id: z.optional(z.union([
        z.uuid(),
        z.null()
    ])),
    created_at: z.iso.datetime(),
    updated_at: z.iso.datetime()
});

/**
 * ResumeCreate
 */
export const zResumeCreate = z.object({
    resume_name: z.string(),
    resume_version: z.optional(z.string()).default('1.0'),
    status: z.optional(z.string()).default('draft'),
    language: z.optional(z.string()).default('ko'),
    purpose: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    notes: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    is_current: z.optional(z.boolean()).default(true),
    user_id: z.uuid(),
    profile_id: z.optional(z.union([
        z.uuid(),
        z.null()
    ])),
    created_by: z.optional(z.union([
        z.uuid(),
        z.null()
    ])),
    previous_version_id: z.optional(z.union([
        z.uuid(),
        z.null()
    ]))
});

/**
 * ResumeRead
 */
export const zResumeRead = z.object({
    resume_name: z.string(),
    resume_version: z.optional(z.string()).default('1.0'),
    status: z.optional(z.string()).default('draft'),
    language: z.optional(z.string()).default('ko'),
    purpose: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    notes: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    is_current: z.optional(z.boolean()).default(true),
    id: z.uuid(),
    user_id: z.uuid(),
    profile_id: z.optional(z.union([
        z.uuid(),
        z.null()
    ])),
    created_at: z.iso.datetime(),
    updated_at: z.iso.datetime(),
    created_by: z.optional(z.union([
        z.uuid(),
        z.null()
    ])),
    previous_version_id: z.optional(z.union([
        z.uuid(),
        z.null()
    ]))
});

/**
 * ResumeSectionCreate
 */
export const zResumeSectionCreate = z.object({
    section_type: z.string(),
    section_name: z.string(),
    display_order: z.optional(z.int()).default(0),
    is_included: z.optional(z.boolean()).default(true),
    resume_id: z.optional(z.union([
        z.uuid(),
        z.null()
    ]))
});

/**
 * ResumeSectionRead
 */
export const zResumeSectionRead = z.object({
    section_type: z.string(),
    section_name: z.string(),
    display_order: z.optional(z.int()).default(0),
    is_included: z.optional(z.boolean()).default(true),
    id: z.uuid(),
    resume_id: z.optional(z.union([
        z.uuid(),
        z.null()
    ])),
    created_at: z.iso.datetime()
});

/**
 * ResumeSummary
 */
export const zResumeSummary = z.object({
    total_records: z.int().gte(0)
});

/**
 * RoleRead
 */
export const zRoleRead = z.object({
    name: z.enum([
        'admin',
        'manager',
        'user'
    ]),
    id: z.int()
});

/**
 * TrainingProgramCreate
 */
export const zTrainingProgramCreate = z.object({
    program_name: z.string(),
    start_date: z.iso.date(),
    end_date: z.iso.date(),
    organizing_institution: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    completion_status: z.optional(z.boolean()).default(false),
    display_order: z.optional(z.int()).default(0),
    resume_id: z.optional(z.union([
        z.uuid(),
        z.null()
    ]))
});

/**
 * TrainingProgramRead
 */
export const zTrainingProgramRead = z.object({
    program_name: z.string(),
    start_date: z.iso.date(),
    end_date: z.iso.date(),
    organizing_institution: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    completion_status: z.optional(z.boolean()).default(false),
    display_order: z.optional(z.int()).default(0),
    id: z.uuid(),
    resume_id: z.optional(z.union([
        z.uuid(),
        z.null()
    ])),
    created_at: z.iso.datetime()
});

/**
 * UserCreate
 */
export const zUserCreate = z.object({
    username: z.string().min(3).max(50),
    name: z.optional(z.union([
        z.string().max(100),
        z.null()
    ])),
    profile_photo_url: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    is_active: z.optional(z.boolean()).default(true),
    email: z.email(),
    password: z.optional(z.union([
        z.string().min(8),
        z.null()
    ])),
    google_id: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    google_refresh_token: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    google_access_token: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    google_auth_active: z.optional(z.boolean()).default(false),
    role_name: z.optional(z.union([
        z.enum([
            'admin',
            'manager',
            'user'
        ]),
        z.null()
    ]))
});

/**
 * UserRead
 */
export const zUserRead = z.object({
    username: z.string().min(3).max(50),
    name: z.optional(z.union([
        z.string().max(100),
        z.null()
    ])),
    profile_photo_url: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    is_active: z.optional(z.boolean()).default(true),
    id: z.uuid(),
    email: z.email(),
    role: zRoleRead,
    google_id: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    google_auth_active: z.boolean(),
    last_login: z.optional(z.union([
        z.iso.datetime(),
        z.null()
    ])),
    created_at: z.iso.datetime(),
    updated_at: z.iso.datetime(),
    is_deleted: z.boolean()
});

/**
 * LoginResponse
 */
export const zLoginResponse = z.object({
    access_token: z.string(),
    token_type: z.optional(z.literal("bearer")).default('bearer'),
    expires_in: z.int().gte(0),
    user: zUserRead
});

/**
 * UserSessionRead
 */
export const zUserSessionRead = z.object({
    session_token: z.string(),
    refresh_token: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    expires_at: z.iso.datetime(),
    user_agent: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    ip_address: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    is_active: z.optional(z.boolean()).default(true),
    id: z.uuid(),
    user_id: z.optional(z.union([
        z.uuid(),
        z.null()
    ])),
    created_at: z.iso.datetime()
});

/**
 * UserUpdate
 */
export const zUserUpdate = z.object({
    email: z.optional(z.union([
        z.email(),
        z.null()
    ])),
    username: z.optional(z.union([
        z.string().min(3).max(50),
        z.null()
    ])),
    name: z.optional(z.union([
        z.string().max(100),
        z.null()
    ])),
    profile_photo_url: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    is_active: z.optional(z.union([
        z.boolean(),
        z.null()
    ])),
    password: z.optional(z.union([
        z.string().min(8),
        z.null()
    ])),
    google_id: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    google_refresh_token: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    google_access_token: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    google_auth_active: z.optional(z.union([
        z.boolean(),
        z.null()
    ])),
    role_name: z.optional(z.union([
        z.enum([
            'admin',
            'manager',
            'user'
        ]),
        z.null()
    ])),
    is_deleted: z.optional(z.union([
        z.boolean(),
        z.null()
    ]))
});

/**
 * ValidationError
 */
export const zValidationError = z.object({
    loc: z.array(z.union([
        z.string(),
        z.int()
    ])),
    msg: z.string(),
    type: z.string()
});

/**
 * HTTPValidationError
 */
export const zHttpValidationError = z.object({
    detail: z.optional(z.array(zValidationError))
});

/**
 * WorkExperienceCreate
 */
export const zWorkExperienceCreate = z.object({
    start_date: z.iso.date(),
    end_date: z.optional(z.union([
        z.iso.date(),
        z.null()
    ])),
    organization: z.string(),
    department: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    position: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    responsibilities: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    current_job: z.optional(z.boolean()).default(false),
    display_order: z.optional(z.int()).default(0),
    resume_id: z.optional(z.union([
        z.uuid(),
        z.null()
    ]))
});

/**
 * WorkExperienceRead
 */
export const zWorkExperienceRead = z.object({
    start_date: z.iso.date(),
    end_date: z.optional(z.union([
        z.iso.date(),
        z.null()
    ])),
    organization: z.string(),
    department: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    position: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    responsibilities: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    current_job: z.optional(z.boolean()).default(false),
    display_order: z.optional(z.int()).default(0),
    id: z.uuid(),
    resume_id: z.optional(z.union([
        z.uuid(),
        z.null()
    ])),
    created_at: z.iso.datetime()
});

/**
 * ResumeDetail
 */
export const zResumeDetail = z.object({
    resume_name: z.string(),
    resume_version: z.optional(z.string()).default('1.0'),
    status: z.optional(z.string()).default('draft'),
    language: z.optional(z.string()).default('ko'),
    purpose: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    notes: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    is_current: z.optional(z.boolean()).default(true),
    id: z.uuid(),
    user_id: z.uuid(),
    profile_id: z.optional(z.union([
        z.uuid(),
        z.null()
    ])),
    created_at: z.iso.datetime(),
    updated_at: z.iso.datetime(),
    created_by: z.optional(z.union([
        z.uuid(),
        z.null()
    ])),
    previous_version_id: z.optional(z.union([
        z.uuid(),
        z.null()
    ])),
    personal_profiles: z.optional(z.array(zPersonalProfileRead)),
    education_history: z.optional(z.array(zEducationHistoryRead)),
    family_members: z.optional(z.array(zFamilyMemberRead)),
    work_experience: z.optional(z.array(zWorkExperienceRead)),
    organizational_activities: z.optional(z.array(zOrganizationalActivityRead)),
    training_programs: z.optional(z.array(zTrainingProgramRead)),
    certifications: z.optional(z.array(zCertificationRead)),
    awards: z.optional(z.array(zAwardRead)),
    discipline_records: z.optional(z.array(zDisciplineRecordRead)),
    additional_remarks: z.optional(z.array(zAdditionalRemarkRead)),
    sections: z.optional(z.array(zResumeSectionRead))
});

export const zAuthGetStatusData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * Successful Response
 */
export const zAuthGetStatusResponse = zAuthStatus;

export const zAuthLoginData = z.object({
    body: zLoginRequest,
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * Successful Response
 */
export const zAuthLoginResponse = zLoginResponse;

export const zAuthRequestPasswordResetData = z.object({
    body: zPasswordResetRequest,
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * Successful Response
 */
export const zAuthRequestPasswordResetResponse = zPasswordResetToken;

export const zAuthResetPasswordData = z.object({
    body: zPasswordResetConfirm,
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * Successful Response
 */
export const zAuthResetPasswordResponse = zUserRead;

export const zAuthListUsersData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.object({
        limit: z.optional(z.int().gte(1).lte(100)).default(50),
        offset: z.optional(z.int().gte(0)).default(0)
    }))
});

/**
 * Response Auth-List Users
 *
 * Successful Response
 */
export const zAuthListUsersResponse = z.array(zUserRead);

export const zAuthCreateUserData = z.object({
    body: zUserCreate,
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * Successful Response
 */
export const zAuthCreateUserResponse = zUserRead;

export const zAuthGetUserData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        user_id: z.uuid()
    }),
    query: z.optional(z.never())
});

/**
 * Successful Response
 */
export const zAuthGetUserResponse = zUserRead;

export const zAuthUpdateUserData = z.object({
    body: zUserUpdate,
    path: z.object({
        user_id: z.uuid()
    }),
    query: z.optional(z.never())
});

/**
 * Successful Response
 */
export const zAuthUpdateUserResponse = zUserRead;

export const zAuthActivateGoogleLoginData = z.object({
    body: zGoogleAuthActivate,
    path: z.object({
        user_id: z.uuid()
    }),
    query: z.optional(z.never())
});

/**
 * Successful Response
 */
export const zAuthActivateGoogleLoginResponse = zUserRead;

export const zAuthUpdateGoogleTokensData = z.object({
    body: zGoogleTokenUpdate,
    path: z.object({
        user_id: z.uuid()
    }),
    query: z.optional(z.never())
});

/**
 * Successful Response
 */
export const zAuthUpdateGoogleTokensResponse = zUserRead;

export const zAuthDeactivateGoogleLoginData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        user_id: z.uuid()
    }),
    query: z.optional(z.never())
});

/**
 * Successful Response
 */
export const zAuthDeactivateGoogleLoginResponse = zUserRead;

export const zResumesListResumesData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.object({
        limit: z.optional(z.int().gte(1).lte(100)).default(50),
        offset: z.optional(z.int().gte(0)).default(0),
        user_id: z.optional(z.union([
            z.uuid(),
            z.null()
        ]))
    }))
});

/**
 * Response Resumes-List Resumes
 *
 * Successful Response
 */
export const zResumesListResumesResponse = z.array(zResumeRead);

export const zResumesCreateResumeData = z.object({
    body: zResumeCreate,
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * Successful Response
 */
export const zResumesCreateResumeResponse = zResumeRead;

export const zResumesSummaryData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * Successful Response
 */
export const zResumesSummaryResponse = zResumeSummary;

export const zResumesDeleteResumeData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        resume_id: z.uuid()
    }),
    query: z.optional(z.never())
});

/**
 * Successful Response
 */
export const zResumesDeleteResumeResponse = z.void();

export const zResumesGetResumeData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        resume_id: z.uuid()
    }),
    query: z.optional(z.never())
});

/**
 * Successful Response
 */
export const zResumesGetResumeResponse = zResumeRead;

export const zResumesUpdateResumeData = z.object({
    body: zResumeCreate,
    path: z.object({
        resume_id: z.uuid()
    }),
    query: z.optional(z.never())
});

/**
 * Successful Response
 */
export const zResumesUpdateResumeResponse = zResumeRead;

export const zResumesGetFullResumeData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        resume_id: z.uuid()
    }),
    query: z.optional(z.never())
});

/**
 * Successful Response
 */
export const zResumesGetFullResumeResponse = zResumeDetail;

export const zResumesListProfilesData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        resume_id: z.uuid()
    }),
    query: z.optional(z.never())
});

/**
 * Response Resumes-List Profiles
 *
 * Successful Response
 */
export const zResumesListProfilesResponse = z.array(zPersonalProfileRead);

export const zResumesCreateProfileData = z.object({
    body: zPersonalProfileCreate,
    path: z.object({
        resume_id: z.uuid()
    }),
    query: z.optional(z.never())
});

/**
 * Successful Response
 */
export const zResumesCreateProfileResponse = zPersonalProfileRead;

export const zResumesDeleteProfileData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        profile_id: z.uuid()
    }),
    query: z.optional(z.never())
});

/**
 * Successful Response
 */
export const zResumesDeleteProfileResponse = z.void();

export const zResumesListEducationData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        resume_id: z.uuid()
    }),
    query: z.optional(z.never())
});

/**
 * Response Resumes-List Education
 *
 * Successful Response
 */
export const zResumesListEducationResponse = z.array(zEducationHistoryRead);

export const zResumesCreateEducationData = z.object({
    body: zEducationHistoryCreate,
    path: z.object({
        resume_id: z.uuid()
    }),
    query: z.optional(z.never())
});

/**
 * Successful Response
 */
export const zResumesCreateEducationResponse = zEducationHistoryRead;

export const zResumesDeleteEducationData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        entry_id: z.uuid()
    }),
    query: z.optional(z.never())
});

/**
 * Successful Response
 */
export const zResumesDeleteEducationResponse = z.void();

export const zResumesListFamilyData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        resume_id: z.uuid()
    }),
    query: z.optional(z.never())
});

/**
 * Response Resumes-List Family
 *
 * Successful Response
 */
export const zResumesListFamilyResponse = z.array(zFamilyMemberRead);

export const zResumesCreateFamilyMemberData = z.object({
    body: zFamilyMemberCreate,
    path: z.object({
        resume_id: z.uuid()
    }),
    query: z.optional(z.never())
});

/**
 * Successful Response
 */
export const zResumesCreateFamilyMemberResponse = zFamilyMemberRead;

export const zResumesDeleteFamilyMemberData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        member_id: z.uuid()
    }),
    query: z.optional(z.never())
});

/**
 * Successful Response
 */
export const zResumesDeleteFamilyMemberResponse = z.void();

export const zResumesListWorkData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        resume_id: z.uuid()
    }),
    query: z.optional(z.never())
});

/**
 * Response Resumes-List Work
 *
 * Successful Response
 */
export const zResumesListWorkResponse = z.array(zWorkExperienceRead);

export const zResumesCreateWorkExperienceData = z.object({
    body: zWorkExperienceCreate,
    path: z.object({
        resume_id: z.uuid()
    }),
    query: z.optional(z.never())
});

/**
 * Successful Response
 */
export const zResumesCreateWorkExperienceResponse = zWorkExperienceRead;

export const zResumesDeleteWorkExperienceData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        experience_id: z.uuid()
    }),
    query: z.optional(z.never())
});

/**
 * Successful Response
 */
export const zResumesDeleteWorkExperienceResponse = z.void();

export const zResumesListActivitiesData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        resume_id: z.uuid()
    }),
    query: z.optional(z.never())
});

/**
 * Response Resumes-List Activities
 *
 * Successful Response
 */
export const zResumesListActivitiesResponse = z.array(zOrganizationalActivityRead);

export const zResumesCreateActivityData = z.object({
    body: zOrganizationalActivityCreate,
    path: z.object({
        resume_id: z.uuid()
    }),
    query: z.optional(z.never())
});

/**
 * Successful Response
 */
export const zResumesCreateActivityResponse = zOrganizationalActivityRead;

export const zResumesDeleteActivityData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        activity_id: z.uuid()
    }),
    query: z.optional(z.never())
});

/**
 * Successful Response
 */
export const zResumesDeleteActivityResponse = z.void();

export const zResumesListTrainingData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        resume_id: z.uuid()
    }),
    query: z.optional(z.never())
});

/**
 * Response Resumes-List Training
 *
 * Successful Response
 */
export const zResumesListTrainingResponse = z.array(zTrainingProgramRead);

export const zResumesCreateTrainingData = z.object({
    body: zTrainingProgramCreate,
    path: z.object({
        resume_id: z.uuid()
    }),
    query: z.optional(z.never())
});

/**
 * Successful Response
 */
export const zResumesCreateTrainingResponse = zTrainingProgramRead;

export const zResumesDeleteTrainingData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        program_id: z.uuid()
    }),
    query: z.optional(z.never())
});

/**
 * Successful Response
 */
export const zResumesDeleteTrainingResponse = z.void();

export const zResumesListCertificationsData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        resume_id: z.uuid()
    }),
    query: z.optional(z.never())
});

/**
 * Response Resumes-List Certifications
 *
 * Successful Response
 */
export const zResumesListCertificationsResponse = z.array(zCertificationRead);

export const zResumesCreateCertificationData = z.object({
    body: zCertificationCreate,
    path: z.object({
        resume_id: z.uuid()
    }),
    query: z.optional(z.never())
});

/**
 * Successful Response
 */
export const zResumesCreateCertificationResponse = zCertificationRead;

export const zResumesDeleteCertificationData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        certification_id: z.uuid()
    }),
    query: z.optional(z.never())
});

/**
 * Successful Response
 */
export const zResumesDeleteCertificationResponse = z.void();

export const zResumesListAwardsData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        resume_id: z.uuid()
    }),
    query: z.optional(z.never())
});

/**
 * Response Resumes-List Awards
 *
 * Successful Response
 */
export const zResumesListAwardsResponse = z.array(zAwardRead);

export const zResumesCreateAwardData = z.object({
    body: zAwardCreate,
    path: z.object({
        resume_id: z.uuid()
    }),
    query: z.optional(z.never())
});

/**
 * Successful Response
 */
export const zResumesCreateAwardResponse = zAwardRead;

export const zResumesDeleteAwardData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        award_id: z.uuid()
    }),
    query: z.optional(z.never())
});

/**
 * Successful Response
 */
export const zResumesDeleteAwardResponse = z.void();

export const zResumesListDisciplineData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        resume_id: z.uuid()
    }),
    query: z.optional(z.never())
});

/**
 * Response Resumes-List Discipline
 *
 * Successful Response
 */
export const zResumesListDisciplineResponse = z.array(zDisciplineRecordRead);

export const zResumesCreateDisciplineRecordData = z.object({
    body: zDisciplineRecordCreate,
    path: z.object({
        resume_id: z.uuid()
    }),
    query: z.optional(z.never())
});

/**
 * Successful Response
 */
export const zResumesCreateDisciplineRecordResponse = zDisciplineRecordRead;

export const zResumesDeleteDisciplineRecordData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        record_id: z.uuid()
    }),
    query: z.optional(z.never())
});

/**
 * Successful Response
 */
export const zResumesDeleteDisciplineRecordResponse = z.void();

export const zResumesListRemarksData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        resume_id: z.uuid()
    }),
    query: z.optional(z.never())
});

/**
 * Response Resumes-List Remarks
 *
 * Successful Response
 */
export const zResumesListRemarksResponse = z.array(zAdditionalRemarkRead);

export const zResumesCreateRemarkData = z.object({
    body: zAdditionalRemarkCreate,
    path: z.object({
        resume_id: z.uuid()
    }),
    query: z.optional(z.never())
});

/**
 * Successful Response
 */
export const zResumesCreateRemarkResponse = zAdditionalRemarkRead;

export const zResumesDeleteRemarkData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        remark_id: z.uuid()
    }),
    query: z.optional(z.never())
});

/**
 * Successful Response
 */
export const zResumesDeleteRemarkResponse = z.void();

export const zResumesListSectionsData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        resume_id: z.uuid()
    }),
    query: z.optional(z.never())
});

/**
 * Response Resumes-List Sections
 *
 * Successful Response
 */
export const zResumesListSectionsResponse = z.array(zResumeSectionRead);

export const zResumesCreateSectionData = z.object({
    body: zResumeSectionCreate,
    path: z.object({
        resume_id: z.uuid()
    }),
    query: z.optional(z.never())
});

/**
 * Successful Response
 */
export const zResumesCreateSectionResponse = zResumeSectionRead;

export const zResumesDeleteSectionData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        section_id: z.uuid()
    }),
    query: z.optional(z.never())
});

/**
 * Successful Response
 */
export const zResumesDeleteSectionResponse = z.void();

export const zResumesUpdateSectionData = z.object({
    body: zResumeSectionCreate,
    path: z.object({
        section_id: z.uuid()
    }),
    query: z.optional(z.never())
});

/**
 * Successful Response
 */
export const zResumesUpdateSectionResponse = zResumeSectionRead;

export const zResumesListUserSessionsData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        user_id: z.uuid()
    }),
    query: z.optional(z.never())
});

/**
 * Response Resumes-List User Sessions
 *
 * Successful Response
 */
export const zResumesListUserSessionsResponse = z.array(zUserSessionRead);

export const zResumesListEmailTokensData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        user_id: z.uuid()
    }),
    query: z.optional(z.never())
});

/**
 * Response Resumes-List Email Tokens
 *
 * Successful Response
 */
export const zResumesListEmailTokensResponse = z.array(zEmailVerificationTokenRead);
